import { unsplashImage } from "../images";
import type { FlowerGuide } from "../types";

const TEAM = "BlossomPot Editorial Team";
const UPDATED = "2026-08-16";

export const coreFlowerGuides: FlowerGuide[] = [
  {
    slug: "rose",
    name: "Rose",
    commonNames: ["Garden rose", "Cut rose", "Rosa"],
    botanicalName: "Rosa",
    family: "Rosaceae",
    letter: "R",
    shortDescription: "The world's best-known cut flower, with colour-specific meanings.",
    glance:
      "A rose is a flowering plant in the genus Rosa, widely grown and used as a cut flower. Roses are available in many colours and are traditionally associated with love, affection, celebration and remembrance depending on colour and cultural context. Commercial cut roses are produced year-round in greenhouses and export regions, so florist availability is not limited to a local garden season.",
    whatIs:
      "A rose is a woody flowering plant in the genus Rosa (family Rosaceae). Florists usually mean cultivated cut roses — hybrid teas, spray roses and garden-style roses — rather than wild species roses.",
    about: [
      "Roses have been cultivated for thousands of years in Asia, the Middle East and later Europe. Today the genus includes hundreds of species and many thousands of cultivars. Most supermarket and florist roses are modern hybrids selected for stem length, colour, bud form and shipping toughness rather than for the scent of an old garden rose.",
      "A typical cut rose has a woody stem, compound leaves and a flower that may be a tight hybrid-tea bud or a looser, many-petalled garden form. Colour ranges from deep red and pink through white, cream, yellow, orange, peach and lavender. Fragrance varies widely: some cultivars are strongly scented, many modern cut roses are only lightly scented or nearly scentless.",
      "Roses grow in temperate climates worldwide. Outdoor garden flowering is usually strongest from late spring through autumn in the Northern Hemisphere, and in the opposite months in Australia. That garden calendar is not the same as florist supply. Large volumes of cut roses are grown in equatorial highland regions such as Colombia, Ecuador and Kenya, and in Dutch and other greenhouse systems, then shipped to wholesalers.",
      "Roses remain popular because they are instantly recognised, photograph well, and carry a long history of gift-giving. They also travel reasonably well when harvested at the right bud stage and kept cool — which is why they dominate Valentine's Day, anniversary and mixed-bouquet work.",
    ],
    meaning: [
      "Rose symbolism is widely shared in Western gifting, but it is not a universal language. Victorian floriography, religious art, and modern florist marketing have all shaped the associations people expect today. Colour, number of stems, and the relationship between giver and recipient matter as much as the flower itself.",
      "Red roses are traditionally associated with romantic love and deep affection. Pink roses are often used to express admiration, gratitude or gentler affection. White roses are frequently chosen for weddings, new beginnings and remembrance. Yellow roses are commonly linked with friendship and joy, though older European traditions sometimes connected yellow with jealousy — context matters.",
      "Orange and coral roses are often used for enthusiasm and passion. Peach roses can read as sincerity or sympathy depending on the arrangement. Lavender or purple roses are sometimes associated with enchantment or love at first sight in modern florist copy. None of these meanings is obligatory; they are cultural conventions, not botanical facts.",
    ],
    colours: [
      { colour: "red", label: "Red", association: "Often used to express romantic love and deep affection", occasions: ["romantic", "anniversary", "valentines-day"] },
      { colour: "pink", label: "Pink", association: "Traditionally associated with admiration, gratitude and gentler affection", occasions: ["birthday", "thank-you", "mothers-day"] },
      { colour: "white", label: "White", association: "Often used for purity, elegance, weddings and remembrance", occasions: ["wedding", "sympathy", "congratulations"] },
      { colour: "yellow", label: "Yellow", association: "Commonly linked with friendship and celebration; older meanings vary", occasions: ["birthday", "congratulations", "just-because"] },
      { colour: "orange", label: "Orange", association: "Often chosen for energy, fascination and warmer passion", occasions: ["congratulations", "romantic"] },
      { colour: "peach", label: "Peach", association: "Frequently used for sincerity, sympathy or soft romance", occasions: ["thank-you", "sympathy", "anniversary"] },
      { colour: "purple", label: "Lavender / purple", association: "Modern florist use often suggests enchantment or uniqueness", occasions: ["wedding", "romantic"] },
    ],
    varieties: [
      { name: "Hybrid tea", summary: "Classic long-stemmed florist rose with a high-centred bud; the form most people picture as a dozen roses." },
      { name: "Floribunda", summary: "Clusters of smaller blooms on one stem; useful for colour and a garden look." },
      { name: "Grandiflora", summary: "Taller plants combining hybrid-tea form with clustered flowering." },
      { name: "Garden roses", summary: "Looser, many-petalled roses grown for a romantic, old-fashioned look in weddings and luxury bouquets." },
      { name: "Spray roses", summary: "Several smaller blooms per stem; popular for texture in mixed arrangements." },
      { name: "English roses", summary: "David Austin and similar garden-style groups, often more fragrant, with cupped or rosette form." },
    ],
    season: ["year-round"],
    seasonSummary: "Garden roses peak in warm months; commercial cut roses are available all year through greenhouse and import supply.",
    seasonDetail: [
      "Local growing season and florist availability are different things. In much of the USA, Canada, the UK and northern Europe, outdoor roses typically flower from late spring until autumn frost. In Australia, the main garden flush is closer to October–May depending on climate zone.",
      "Cut roses for delivery are rarely limited to that outdoor window. Wholesalers buy from greenhouse growers and from export farms near the equator, where day length and highland climate support year-round production. That is why red roses can be ordered in January as well as June.",
      "Price and quality still move with demand and weather. Valentine's Day, Mother's Day and major wedding weekends raise wholesale prices. Heatwaves, transport delays and holiday airport congestion can shorten vase life if the cold chain is broken. Peak-garden months can offer more garden-style and locally grown stems in some markets.",
    ],
    marketNotes: [
      { market: "us", summary: "Cut roses are a year-round US florist staple, with a sharp demand spike around Valentine's Day and Mother's Day (second Sunday in May)." },
      { market: "canada", summary: "Similar year-round import supply; outdoor garden season is shorter in much of Canada than in the southern US." },
      { market: "uk", summary: "British-grown garden roses are seasonal; most everyday florist roses are imported. Mother's Day in the UK falls in March (Mothering Sunday), earlier than the US date." },
      { market: "europe", summary: "The Netherlands remains a major auction and distribution hub; southern Europe also grows outdoor roses in warmer months." },
      { market: "australia", summary: "Seasons are reversed. Local garden roses peak in the Australian spring and summer; imports fill gaps." },
      { market: "uae", summary: "Almost all cut roses are imported. Cooler months are kinder to vase life after delivery; summer heat requires careful handling." },
    ],
    origin: "Wild roses are native mainly to Asia, with species also in Europe, North America and North Africa. Most modern cut roses are complex hybrids.",
    habitat: "Temperate gardens, commercial greenhouses, and highland tropical farms used for export production.",
    appearance: "Woody stems, compound leaves, and flowers from simple five-petalled species forms to densely petalled modern cultivars.",
    fragrance: "Varies by cultivar — from nearly scentless modern hybrids to strongly fragrant garden and English roses.",
    vaseLife: "Typically several days to about a week or more with clean water, recut stems and cool placement. Exact days vary by cultivar, harvest stage and care — do not treat any single number as guaranteed.",
    cutFlower: true,
    bouquetUse: "Roses are the default romantic bouquet flower and a core ingredient in mixed celebration designs.",
    floristUses: "Dozen-stem bunches, bridal work, corsages, sympathy pieces, and colour-themed mixed bouquets.",
    care: [
      "Unwrap and recut stems at an angle, then place immediately in clean, lukewarm water.",
      "Remove leaves that would sit below the waterline to slow bacterial growth.",
      "Use the flower food packet if supplied, or change water every one to two days.",
      "Keep the vase away from direct sun, heaters, and ripening fruit (ethylene shortens life).",
      "If heads droop, recut stems and check that the water is fresh; some tight buds open over several days.",
    ],
    occasions: ["romantic", "anniversary", "valentines-day", "birthday", "wedding", "congratulations", "sympathy"],
    occasionNotes: [
      "Red roses remain the most requested anniversary and Valentine's flower in Western markets.",
      "Soft pinks and mixed palettes often feel more birthday-friendly than a formal dozen reds.",
      "White roses appear in both wedding and sympathy work — the styling and card message change the reading.",
    ],
    petSafety:
      "The ASPCA lists roses (Rosa spp.) as non-toxic to dogs and cats. Thorns can still injure mouths and paws, and any plant material can upset a stomach if eaten in quantity.",
    pollenNotes:
      "Many modern cut roses produce little obvious pollen compared with lilies. People with strong fragrance sensitivity may still react to highly scented garden roses.",
    facts: [
      "The rose is among the oldest cultivated ornamental plants, with a documented history in China and the Middle East long before European breeding booms.",
      "Cut-rose production for export is concentrated in a few highland growing regions because cool nights and strong light produce long, straight stems.",
      "Fragrance and vase life are often a trade-off in breeding; very long-lasting supermarket roses are frequently less scented.",
    ],
    relatedFlowers: ["peony", "tulip", "carnation", "lisianthus", "ranunculus"],
    relatedColours: ["red", "pink", "white", "yellow"],
    relatedOccasions: ["romantic", "anniversary", "valentines-day", "wedding"],
    relatedCareSlug: "how-to-care-for-roses",
    shopQuery: "rose",
    shopCategory: "flowers",
    faqs: [
      { q: "Are roses available all year?", a: "Yes, as commercial cut flowers. Local garden roses are seasonal, but florist roses are grown in greenhouses and export farms throughout the year." },
      { q: "How long do roses last in a vase?", a: "With clean water, recut stems and a cool room, many cut roses last several days to around a week. Variety, travel time and care all change the result." },
      { q: "What do red roses mean?", a: "In much of Western gifting they are traditionally associated with romantic love. The meaning is cultural, not scientific, and other colours carry different conventions." },
      { q: "What do white roses mean?", a: "White roses are often used for weddings, elegance and remembrance. In sympathy work they can signal honour or farewell; in bridal work they more often signal formality." },
      { q: "Are roses good for birthdays?", a: "Yes. Pink, mixed or garden-style roses often feel more celebratory than a strictly romantic red dozen, depending on the relationship." },
      { q: "Do roses have a strong fragrance?", a: "Some do. Many modern long-stemmed cut roses are bred more for form and shipping than scent. Ask for garden or English-style roses if fragrance matters." },
      { q: "Are roses safe around pets?", a: "Roses are generally listed as non-toxic to cats and dogs, but thorns are a physical hazard and chewing any plant can cause stomach upset." },
    ],
    sources: [
      { label: "Royal Horticultural Society — Rosa", url: "https://www.rhs.org.uk/plants/rosa" },
      { label: "ASPCA — Rose", url: "https://www.aspca.org/pet-care/animal-poison-control/toxic-and-non-toxic-plants/rose" },
      { label: "Society of American Florists — flower facts and care guidance" },
      { label: "Kew / botanical references on Rosa distribution and cultivation history" },
    ],
    images: [
      unsplashImage("photo-1518621012118-4d0d512fdd5b", "Red garden rose with layered petals", "red-rose-flower-close-up.jpg", "Annie Spratt", "hero"),
      unsplashImage("photo-1455659817273-f093b0cdc19e", "Soft pink roses in a bouquet", "pink-rose-bouquet.jpg", "Annie Spratt", "bouquet"),
    ],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Rose Flower Guide: Meaning, Colours, Types & Care | BlossomPot",
    seoDescription:
      "Learn about roses, including colours, traditional meanings, varieties, seasons and care. Discover rose bouquets and flower delivery from BlossomPot.",
    h1: "Rose: Meaning, Colours, Varieties & Care Guide",
  },
  {
    slug: "tulip",
    name: "Tulip",
    commonNames: ["Garden tulip"],
    botanicalName: "Tulipa",
    family: "Liliaceae",
    letter: "T",
    shortDescription: "Spring bulb flower with many forms, from Triumph to Parrot.",
    glance:
      "A tulip is a spring-flowering bulb in the genus Tulipa, native to Central Asia and long associated with the Netherlands. Tulips are among the most important commercial cut flowers of late winter and spring. Colour and form vary widely; symbolism is often linked with affection, though it is not universal.",
    whatIs:
      "Tulips are bulbous perennials in the lily family. Florists sell them as cut stems that continue to elongate in the vase, and as potted forced bulbs in late winter.",
    about: [
      "Wild tulips originated in the mountain regions of Central Asia. They reached the Ottoman court and, in the sixteenth and seventeenth centuries, became a European obsession — most famously in the Dutch Republic. The Netherlands remains a major centre of breeding, forcing and export.",
      "A tulip flower is typically cup- or star-shaped with six tepals. Modern groups include Single Early, Double Early, Triumph, Darwin Hybrid, Lily-flowered, Fringed and Parrot tulips. Heights, bloom times and petal shapes differ enough that 'tulip' is a category, not a single look.",
      "Cut tulips are a cool-season crop. They are forced under controlled conditions so that stems can reach markets from mid-winter through late spring in the Northern Hemisphere. Outside that window, supply thins and prices usually rise. Australia’s commercial tulip season sits in the opposite half of the year.",
      "People choose tulips because they feel seasonal and optimistic. They are less formally romantic than red roses for many shoppers, which makes them a frequent birthday, Mother's Day and 'just because' flower.",
    ],
    meaning: [
      "In modern Western florist use, tulips are often associated with affection, perfect love and spring renewal. The association is younger and looser than rose colour lore.",
      "Red tulips are sometimes described as a declaration of love. Yellow tulips have been linked with cheerful thoughts or, in older lists, hopeless love. White tulips may be used for forgiveness or respectful affection. These readings vary by source and should be treated as tradition, not fact.",
      "In the Netherlands and much of Europe, tulips also carry a national and seasonal identity that has little to do with romance — they simply mark the arrival of spring.",
    ],
    colours: [
      { colour: "red", label: "Red", association: "Often used for affection or a warmer romantic note", occasions: ["romantic", "birthday"] },
      { colour: "pink", label: "Pink", association: "Soft affection, birthdays and spring gifts", occasions: ["birthday", "mothers-day"] },
      { colour: "yellow", label: "Yellow", association: "Cheer and sunshine; older meanings differ", occasions: ["just-because", "congratulations"] },
      { colour: "white", label: "White", association: "Respect, calm elegance or apology in some traditions", occasions: ["thank-you", "sympathy"] },
      { colour: "purple", label: "Purple", association: "Often chosen for a more regal or modern look", occasions: ["congratulations"] },
      { colour: "orange", label: "Orange", association: "Energy and warmth", occasions: ["birthday", "just-because"] },
    ],
    varieties: [
      { name: "Single Early", summary: "Shorter stems and cup-shaped flowers; among the first groups forced for late winter." },
      { name: "Double Early", summary: "Peony-like layered petals on relatively short stems." },
      { name: "Triumph", summary: "The main commercial cut group — mid-season, strong stems, wide colour range." },
      { name: "Parrot", summary: "Twisted, ruffled tepals; dramatic in boutique bouquets." },
      { name: "Lily-flowered", summary: "Pointed, reflexed tepals that look more elegant and elongated." },
    ],
    season: ["spring", "winter"],
    seasonSummary: "Peak commercial cut-tulip supply is late winter through spring in the Northern Hemisphere; the season reverses in Australia.",
    seasonDetail: [
      "Tulips are a classic example of why 'in season' needs two answers. Outdoors they bloom in spring. Commercially they are forced so that cut stems appear in shops from roughly January to May in the US, Canada, the UK and much of Europe.",
      "Greenhouse and cold-storage techniques extend the window, but summer and early autumn are not natural tulip months in the north. Some product can still be imported from the opposite hemisphere.",
      "Price is usually lowest and quality highest in the core spring window. Heat after delivery makes tulips open and flop faster.",
    ],
    marketNotes: [
      { market: "us", summary: "Strong late-winter and spring presence; a frequent Mother's Day option when the US date falls in May." },
      { market: "canada", summary: "Similar forcing calendar to the northern US; outdoor bloom is later in colder provinces." },
      { market: "uk", summary: "A defining British spring flower. Local and Dutch supply is abundant from late winter." },
      { market: "europe", summary: "The Netherlands dominates breeding and export; tulip season is a cultural event as well as a crop." },
      { market: "australia", summary: "Local tulip festivals and cut supply sit in the Australian spring (roughly September–November)." },
      { market: "uae", summary: "Imported during the Northern Hemisphere season; indoor air-conditioning helps vase life." },
    ],
    origin: "Central Asia, with a long history of cultivation in the Ottoman Empire and the Netherlands.",
    habitat: "Temperate gardens and commercial bulb-forcing operations.",
    appearance: "Smooth stems, strap-like leaves, and six-tepal flowers in cup, double or parrot forms.",
    fragrance: "Usually light; a few cultivars are more noticeably scented.",
    vaseLife: "Often around five to ten days. Stems keep growing and bending toward light, which is normal rather than a fault.",
    cutFlower: true,
    bouquetUse: "Sold as bunches or mixed with spring fillers; they continue to move in the vase.",
    floristUses: "Seasonal bunches, Mother's Day, birthday colour, and modern monochrome designs.",
    care: [
      "Recut stems and use a clean, fairly deep vase — tulips are thirsty and keep growing.",
      "Cool water and a cool room slow opening. Avoid deep warm water if you want them to last.",
      "Do not mix freshly cut tulips with freshly cut daffodils unless the daffodils have been conditioned separately; narcissus sap can shorten other flowers' life.",
      "Support floppy stems with a taller vase rather than wiring, unless a designer has already structured the bunch.",
    ],
    occasions: ["birthday", "romantic", "mothers-day", "congratulations", "just-because"],
    occasionNotes: [
      "Tulips feel seasonal and optimistic, which suits birthdays and spring congratulations.",
      "They can be romantic, but they read less formal than a dozen red roses for many recipients.",
    ],
    petSafety:
      "The ASPCA lists tulips as toxic to dogs and cats. The bulb contains the highest concentration of tulipalin A; keep discarded bulbs and leaves away from pets.",
    pollenNotes: "Generally lower-drama than lilies, but any cut flower can bother highly sensitive people.",
    facts: [
      "Tulip stems elongate after cutting, so a bouquet can look taller on day three than on day one.",
      "Seventeenth-century Dutch 'tulip mania' concerned rare bulbs, not everyday mixed bunches.",
    ],
    relatedFlowers: ["rose", "peony", "ranunculus", "daffodil", "hyacinth"],
    relatedColours: ["pink", "red", "yellow", "white"],
    relatedOccasions: ["birthday", "mothers-day", "romantic"],
    relatedCareSlug: "how-to-care-for-tulips",
    shopQuery: "tulip",
    shopCategory: "flowers",
    faqs: [
      { q: "When are tulips in season?", a: "As cut flowers, mainly late winter and spring in the Northern Hemisphere. Local garden bloom is spring. Australia’s season is roughly the opposite." },
      { q: "Why do tulips keep growing in the vase?", a: "They are geotropic and phototropic — stems elongate and bend toward light after harvest. It is a normal tulip behaviour." },
      { q: "Are tulips safe for cats?", a: "No. Tulips are considered toxic to cats and dogs, especially the bulbs." },
      { q: "Are tulips good for Mother's Day?", a: "In the US, Mother's Day in May often still overlaps late tulip supply. In the UK, Mothering Sunday in March sits in peak tulip season." },
    ],
    sources: [
      { label: "Royal Horticultural Society — Tulipa" },
      { label: "ASPCA — Tulip" },
      { label: "International Flower Bulb Centre / Dutch bulb industry seasonality references" },
    ],
    images: [
      unsplashImage("photo-1520763185298-1b434c919102", "Pink tulips in a spring bunch", "pink-tulip-flowers.jpg", "Annie Spratt", "hero"),
    ],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Tulip Flower Guide: Meaning, Colours, Types & Care | BlossomPot",
    seoDescription:
      "Discover tulip meanings, colours, types and spring seasonality. Learn how tulips differ from roses and how to care for a cut bunch.",
    h1: "Tulip: Meaning, Colours, Types & Care Guide",
  },
  {
    slug: "peony",
    name: "Peony",
    commonNames: ["Garden peony", "Herbaceous peony", "Tree peony"],
    botanicalName: "Paeonia",
    family: "Paeoniaceae",
    letter: "P",
    shortDescription: "Lush, short-season bloom prized for weddings and romance.",
    glance:
      "Peonies are perennial plants in the genus Paeonia, grown for large, often fragrant flowers. Their outdoor season is short — typically late spring into early summer in temperate Northern Hemisphere gardens — which is why they feel special and can be expensive. Commercial growers in both hemispheres and cold-storage techniques extend florist availability beyond a single local month.",
    whatIs:
      "A peony is a long-lived perennial grown for showy flowers. Florists usually mean herbaceous garden peonies (Paeonia lactiflora hybrids) rather than woody tree peonies.",
    about: [
      "Peonies are native to Asia, southern Europe and western North America. Chinese cultivation is ancient; the flower remains an important cultural emblem there. In Europe and North America they became staple garden plants in the nineteenth and twentieth centuries.",
      "Blooms may be single, Japanese, anemone, semi-double or fully double. Colours run from white and blush through coral, pink and deep red. Many cultivars are fragrant; some are only lightly scented.",
      "The local garden season is brief. In much of the US, Canada, the UK and northern Europe, outdoor peonies open for a few weeks between May and early July depending on climate and cultivar. That scarcity is part of their wedding-market appeal.",
      "Florists stretch the season by buying from different latitudes and by holding tight buds in cold storage. Southern Hemisphere harvests can supply northern winter weddings. Still, peak quality and more accessible prices usually coincide with the natural flush.",
    ],
    meaning: [
      "In Chinese tradition peonies are associated with honour, wealth and feminine beauty. In Western wedding culture they more often signal romance and a lush, garden celebration.",
      "Victorian floriography sometimes linked peonies with bashfulness. Modern gifting rarely uses that reading. Treat colour and occasion as more useful than a single 'official' meaning.",
    ],
    colours: [
      { colour: "pink", label: "Pink", association: "Romance, celebration and the classic wedding peony", occasions: ["wedding", "romantic", "mothers-day"] },
      { colour: "white", label: "White / blush", association: "Elegance and formality", occasions: ["wedding", "anniversary"] },
      { colour: "red", label: "Red", association: "Richer, more dramatic affection", occasions: ["anniversary", "romantic"] },
      { colour: "peach", label: "Coral / peach", association: "Modern, warm celebration palettes", occasions: ["wedding", "congratulations"] },
    ],
    varieties: [
      { name: "Herbaceous peonies", summary: "The main cut-flower group; stems die back in winter and return in spring." },
      { name: "Tree peonies", summary: "Woody shrubs with very large flowers; less common as a commercial cut stem." },
      { name: "Itoh / intersectional", summary: "Hybrids combining herbaceous and tree-peony traits; valued in gardens more than in bulk florist bunches." },
    ],
    season: ["spring", "summer"],
    seasonSummary: "A short natural season in late spring; imports and storage extend florist supply at a cost.",
    seasonDetail: [
      "If you want locally grown peonies in the northern US, Canada or the UK, plan for late spring. Exact weeks shift with weather.",
      "Do not assume a florist has no peonies in October. Opposite-hemisphere farms and stored buds can appear, but stems may cost more and open differently.",
      "Coral cultivars often flower earlier than many late pink doubles, so 'peony season' is a window, not a single week.",
    ],
    marketNotes: [
      { market: "us", summary: "Alaska, the Pacific Northwest and cooler northern states are known for quality field peonies; the Lower 48 season is mostly May–June." },
      { market: "canada", summary: "A natural late-spring crop; imports fill weddings outside that window." },
      { market: "uk", summary: "British-grown peonies are a late-spring luxury. Mother's Day in March is usually too early for local peonies." },
      { market: "europe", summary: "Season similar to the UK, with earlier outdoor bloom in the south." },
      { market: "australia", summary: "Local peony production is concentrated in cooler regions during the Australian late spring and early summer." },
      { market: "uae", summary: "Fully imported; treat as a luxury seasonal product rather than an everyday staple." },
    ],
    origin: "Temperate Asia, Europe and western North America.",
    habitat: "Cold-winter gardens; they generally need a winter chill to bloom well.",
    appearance: "Large, often globe-shaped flowers on leafy herbaceous stems.",
    fragrance: "Light to moderate, cultivar-dependent.",
    vaseLife: "Often around five to seven days once open. Tight buds may take a day or two to unfurl.",
    cutFlower: true,
    bouquetUse: "A hero wedding and luxury-romance flower; also used as a single-variety bunch.",
    floristUses: "Bridal bouquets, centrepieces, Mother's Day (US timing), and high-end mixed designs.",
    care: [
      "Recut stems and give them room — opening blooms are large and heavy.",
      "If buds are tight, a slightly warmer room can help them open; once open, cooler air slows them.",
      "Change water often; peony foliage in the water sours quickly.",
      "Support heavy heads if the vase is narrow.",
    ],
    occasions: ["wedding", "anniversary", "romantic", "mothers-day", "birthday"],
    occasionNotes: [
      "Peonies are one of the most requested wedding flowers when the date falls in season.",
      "For US Mother's Day they can align well; for UK Mothering Sunday they usually do not.",
    ],
    petSafety:
      "The ASPCA lists peonies as toxic to dogs, cats and horses if ingested, causing vomiting and other gastrointestinal signs.",
    pollenNotes: "Double forms shed less obvious pollen than many single flowers.",
    facts: [
      "Individual peony plants can live for decades in the right garden.",
      "Ants on peony buds are common in gardens; they are attracted to nectar and are not required for the flower to open.",
    ],
    relatedFlowers: ["rose", "ranunculus", "hydrangea", "gardenia", "lisianthus"],
    relatedColours: ["pink", "white", "peach"],
    relatedOccasions: ["wedding", "romantic", "anniversary"],
    relatedCareSlug: "how-to-care-for-peonies",
    shopQuery: "peony",
    shopCategory: "flowers",
    faqs: [
      { q: "When are peonies in season?", a: "Naturally, late spring to early summer in most Northern Hemisphere gardens. Florists may offer imported or stored stems outside that window." },
      { q: "Why are peonies expensive?", a: "The harvest window is short, stems are bulky to ship, and wedding demand is concentrated. Off-season imports add transport cost." },
      { q: "Are peonies good for weddings?", a: "Yes, when the date overlaps supply. For winter weddings, garden roses or ranunculus are more predictable substitutes." },
      { q: "Are peonies toxic to pets?", a: "They are listed as toxic if eaten. Keep vases out of reach of curious dogs and cats." },
    ],
    sources: [
      { label: "American Peony Society" },
      { label: "Royal Horticultural Society — Paeonia" },
      { label: "ASPCA — Peony" },
    ],
    images: [
      unsplashImage("photo-1561181286-d3fee7d55364", "Pink peony with layered petals", "pink-peony-flower-close-up.jpg", "Annie Spratt", "hero"),
    ],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Peony Flower Guide: Meaning, Season, Colours & Care | BlossomPot",
    seoDescription:
      "Learn when peonies are in season, what they mean, and how to care for cut stems. Explore peony-style bouquets from BlossomPot.",
    h1: "Peony: Meaning, Season, Colours & Care Guide",
  },
  {
    slug: "orchid",
    name: "Orchid",
    commonNames: ["Moth orchid", "Phalaenopsis", "Cymbidium"],
    botanicalName: "Orchidaceae (many genera; Phalaenopsis is the common gift plant)",
    family: "Orchidaceae",
    letter: "O",
    shortDescription: "Diverse family; moth orchids are the most common gift plants.",
    glance:
      "Orchids are a vast plant family (Orchidaceae), not a single flower. As gifts, 'orchid' usually means a potted moth orchid (Phalaenopsis) or cut cymbidium and dendrobium stems. They are associated with refinement and strength. Many common gift orchids are available year-round as greenhouse crops.",
    whatIs:
      "Orchidaceae is one of the largest flowering-plant families. BlossomPot guides focus on the orchids people actually give: potted Phalaenopsis and cut stems used in arrangements.",
    about: [
      "Orchids grow on every continent except Antarctica, from tropical cloud forests to temperate woodlands. Their floral structures are highly specialised for pollinators. That diversity is why a slipper orchid, a vanilla vine and a moth orchid can look unrelated.",
      "The moth orchid (Phalaenopsis) dominates gift retail because it flowers for a long time in a home, ships as a potted plant, and comes in white, pink, purple, yellow and spotted forms. Cut-flower orchids more often include Cymbidium, Dendrobium and occasionally Vanda.",
      "Commercial orchids are greenhouse crops. They are not 'out of season' in the way peonies are, though particular colours or large exhibition cymbidiums may be more plentiful at certain times of year.",
    ],
    meaning: [
      "In many East Asian and Western gifting contexts, orchids suggest refinement, rare beauty and thoughtful respect rather than casual romance.",
      "Victorian floriography assigned various orchid meanings, often linked with luxury. Modern corporate and housewarming gifts use orchids because they last and look architectural, not because of a single coded message.",
    ],
    colours: [
      { colour: "white", label: "White", association: "Elegance and formality", occasions: ["congratulations", "housewarming", "sympathy"] },
      { colour: "pink", label: "Pink", association: "Grace and celebration", occasions: ["birthday", "thank-you"] },
      { colour: "purple", label: "Purple", association: "Admiration and luxury", occasions: ["anniversary", "corporate"] },
      { colour: "yellow", label: "Yellow", association: "Friendship and new beginnings", occasions: ["congratulations"] },
    ],
    varieties: [
      { name: "Phalaenopsis (moth orchid)", summary: "The standard potted gift orchid; long-lasting sprays of flat-faced flowers." },
      { name: "Cymbidium", summary: "Larger sprays used as cut flowers in arrangements and cascades." },
      { name: "Dendrobium", summary: "Slender cut stems common in modern mixed designs." },
    ],
    season: ["year-round"],
    seasonSummary: "Greenhouse production makes common gift orchids a year-round item.",
    seasonDetail: [
      "Do not confuse wild orchid flowering seasons with shop availability. Phalaenopsis is produced continuously.",
      "Cut cymbidiums have historically been more plentiful in cooler months in some markets, but supply is global.",
    ],
    marketNotes: [
      { market: "us", summary: "Widely sold as houseplants in grocery and florist channels all year." },
      { market: "uk", summary: "A standard indoor gift; less tied to British outdoor seasons." },
      { market: "australia", summary: "Year-round indoor gift; some native orchids are a separate wildflower story." },
      { market: "uae", summary: "Popular indoor plant because homes are air-conditioned year-round." },
      { market: "canada", summary: "Year-round houseplant gift; outdoor hardy orchids are a different garden category." },
      { market: "europe", summary: "Major greenhouse production and retail year-round." },
    ],
    origin: "Global tropics and subtropics for most gift genera; temperate species exist but are less common as gifts.",
    habitat: "Many commercial genera are epiphytes in nature — they grow on trees, not in ordinary garden soil.",
    appearance: "Bilateral flowers with a specialised lip (labellum); potted moth orchids have thick leaves and aerial roots.",
    fragrance: "Many Phalaenopsis are unscented; some species and specialist hybrids are fragrant.",
    vaseLife: "Cut orchid stems can last well over a week when kept hydrated. Potted moth orchids may flower for many weeks.",
    cutFlower: true,
    bouquetUse: "Cut stems add a modern, elongated line; potted plants are a separate long-lived gift.",
    floristUses: "Corsages, contemporary arrangements, corporate gifts and housewarming plants.",
    care: [
      "For cut stems: recut, keep water clean, and avoid crushing the hollow or delicate stem ends.",
      "For Phalaenopsis plants: bright indirect light, water when the potting mix is nearly dry, and never leave the pot sitting in stale water.",
      "Do not use ice cubes as a care rule — it is a myth that can over-chill roots. Water thoroughly, then drain.",
      "After flowers fade, a moth orchid may rebloom from a node on the spike or from a new spike, depending on the plant.",
    ],
    occasions: ["anniversary", "congratulations", "housewarming", "corporate", "thank-you"],
    occasionNotes: [
      "Orchids suit recipients who want a living plant rather than a short-lived bouquet.",
      "They are a frequent corporate and congratulations gift because they look considered and last.",
    ],
    petSafety:
      "The ASPCA lists Phalaenopsis orchids as non-toxic to dogs and cats. Other genera can differ — check the specific plant if safety is critical.",
    pollenNotes: "Generally not a high-pollen indoor allergen in the way wind-pollinated trees are, but fragrance and potting media can still bother some people.",
    facts: [
      "Vanilla is an orchid (Vanilla planifolia).",
      "Orchid seeds are dust-like and usually need a fungal partner to germinate in nature.",
    ],
    relatedFlowers: ["rose", "anthurium", "gardenia", "calla-lily", "lily"],
    relatedColours: ["white", "pink", "purple"],
    relatedOccasions: ["congratulations", "housewarming", "anniversary"],
    relatedCareSlug: "how-to-care-for-orchids",
    shopQuery: "orchid",
    shopCategory: "plants",
    faqs: [
      { q: "Are orchids available all year?", a: "Common gift orchids such as Phalaenopsis are greenhouse crops and are sold year-round." },
      { q: "How long do orchids last?", a: "A potted moth orchid can stay in bloom for many weeks. Cut stems often last longer than average mixed-bouquet flowers if hydrated." },
      { q: "Are moth orchids safe for cats?", a: "Phalaenopsis is generally listed as non-toxic to cats and dogs. Confirm the genus if the plant is not a moth orchid." },
      { q: "Do orchids need ice cubes?", a: "No. That popular tip can chill roots. Water when the mix is nearly dry and let excess drain." },
    ],
    sources: [
      { label: "American Orchid Society" },
      { label: "ASPCA — Moth Orchid" },
      { label: "Royal Horticultural Society — Phalaenopsis" },
    ],
    images: [
      unsplashImage("photo-1566938064504-a380d867ac89", "White moth orchid blooms", "white-orchid-flower-close-up.jpg", "Annie Spratt", "hero"),
    ],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Orchid Flower Guide: Types, Meaning & Care Tips | BlossomPot",
    seoDescription:
      "Understand gift orchids, including moth orchids, colours, meanings and care. See how orchids differ from cut roses and when to send one.",
    h1: "Orchid: Types, Meaning & Care Guide",
  },
  {
    slug: "lily",
    name: "Lily",
    commonNames: ["True lily", "Oriental lily", "Asiatic lily", "Easter lily"],
    botanicalName: "Lilium",
    family: "Liliaceae",
    letter: "L",
    shortDescription: "True lilies (Lilium) used in sympathy, Easter, and celebration work.",
    glance:
      "True lilies belong to the genus Lilium. They are important cut flowers, especially Oriental, Asiatic, LA and longiflorum (Easter) types. White lilies are widely used for sympathy and Easter; coloured lilies appear in celebration bouquets. All true lilies are highly toxic to cats.",
    whatIs:
      "A true lily is a bulbous plant in Lilium — not a daylily (Hemerocallis), peace lily (Spathiphyllum) or calla (Zantedeschia), which are unrelated plants that share the word 'lily'.",
    about: [
      "Lilium species are native to temperate Northern Hemisphere regions, especially Asia, Europe and North America. Breeding has produced the main florist groups: Asiatic hybrids (usually unscented, upward-facing), Oriental hybrids (often strongly fragrant, larger flowers), Longiflorum (white trumpet Easter lilies), and LA hybrids (Longiflorum × Asiatic).",
      "Cut lilies are sold in bud so they open over several days. Stamens carry abundant pollen that stains petals, fabric and fur. Many florists remove anthers as flowers open.",
      "Availability is broader than peonies but still has peaks. Easter drives longiflorum demand. Orientals are often associated with mid- to late summer garden bloom, while commercial production supplies much of the year.",
    ],
    meaning: [
      "White lilies are traditionally associated with purity, renewal and, in Christian contexts, the resurrection — which is why they appear at Easter and in many sympathy pieces.",
      "That funeral association is cultural, not mandatory. Coloured Asiatic lilies are routinely used for birthdays and congratulations. In some East Asian contexts chrysanthemums, not lilies, are the primary funeral flower — another reminder that symbolism is local.",
    ],
    colours: [
      { colour: "white", label: "White", association: "Purity, Easter and remembrance", occasions: ["sympathy", "funeral", "wedding"] },
      { colour: "pink", label: "Pink", association: "Prosperity and gentler celebration", occasions: ["birthday", "congratulations"] },
      { colour: "orange", label: "Orange", association: "Energy and confidence", occasions: ["congratulations"] },
      { colour: "yellow", label: "Yellow", association: "Thankfulness and brightness", occasions: ["thank-you", "get-well"] },
    ],
    varieties: [
      { name: "Asiatic hybrids", summary: "Usually unscented, upward-facing, wide colour range; common in mixed bouquets." },
      { name: "Oriental hybrids", summary: "Large, often strongly fragrant flowers such as 'Stargazer' types." },
      { name: "Longiflorum", summary: "White trumpet Easter lily." },
      { name: "LA hybrids", summary: "Longiflorum × Asiatic crosses combining form and colour." },
    ],
    season: ["spring", "summer", "year-round"],
    seasonSummary: "Commercial cut lilies are widely available; Easter and summer garden peaks still shape demand.",
    seasonDetail: [
      "You can usually buy cut lilies outside the outdoor garden season because they are produced as a commercial bulb crop.",
      "Outdoor Lilium in northern gardens typically flower from early to late summer depending on type. Easter lilies are timed to the holiday.",
    ],
    marketNotes: [
      { market: "us", summary: "Easter lilies are a distinct seasonal product. Oriental lilies are a year-round florist item with summer garden overlap." },
      { market: "uk", summary: "Common in sympathy and mixed bouquets; strongly scented Orientals are a matter of taste in small rooms." },
      { market: "australia", summary: "Seasonality follows the Southern Hemisphere garden calendar for outdoor plants; cuts are imported as needed." },
      { market: "canada", summary: "Similar commercial availability to the northern US." },
      { market: "europe", summary: "Major cut-lily production and auction supply through Dutch and other European growers." },
      { market: "uae", summary: "Imported cut stems; fragrance can feel intense in closed, air-conditioned rooms." },
    ],
    origin: "Temperate Northern Hemisphere, with especially rich diversity in Asia.",
    habitat: "Woodland edges and gardens; commercial bulb fields and greenhouses.",
    appearance: "Six tepals, often spotted or brushed, on tall stems with linear leaves.",
    fragrance: "Asiatics usually light or none; Orientals often strong.",
    vaseLife: "Often a week or more as buds continue to open. Individual open flowers last a few days each.",
    cutFlower: true,
    bouquetUse: "Statement stems in mixed bouquets; also sold as a single-variety bunch.",
    floristUses: "Sympathy, Easter, church work, and colourful celebration designs.",
    care: [
      "Recut stems and give tall support. Remove lower leaves.",
      "As each flower opens, pinch or snip off the pollen-bearing anthers to reduce stains and some allergen load.",
      "Keep away from cats — this is a safety issue, not a preference.",
      "Strong Oriental fragrance can overwhelm small bedrooms; a cooler, ventilated room is kinder.",
    ],
    occasions: ["sympathy", "wedding", "congratulations", "funeral", "birthday"],
    occasionNotes: [
      "Ask before sending white lilies if you are unsure how the recipient's culture treats funeral flowers.",
      "Never send true lilies to a home with cats unless the recipient has asked and can keep them out of reach — many vets advise against it entirely.",
    ],
    petSafety:
      "True lilies (Lilium) and daylilies (Hemerocallis) can cause life-threatening kidney failure in cats. Even pollen or vase water is a risk. This is one of the most important pet-safety facts in floristry.",
    pollenNotes:
      "Lily pollen stains and can irritate. Removing anthers as flowers open is standard florist advice. People with fragrance sensitivity should avoid Oriental types.",
    facts: [
      "Peace lilies and calla lilies are not Lilium and have different toxicity profiles — but they are still not 'safe substitutes' without checking.",
      "Lily pollen stains are easier to lift with sticky tape than by rubbing, which drives the pigment in.",
    ],
    relatedFlowers: ["rose", "calla-lily", "orchid", "chrysanthemum", "freesia"],
    relatedColours: ["white", "pink", "orange"],
    relatedOccasions: ["sympathy", "congratulations", "wedding"],
    relatedCareSlug: "how-to-care-for-lilies",
    shopQuery: "lily",
    shopCategory: "flowers",
    faqs: [
      { q: "Are lilies safe for cats?", a: "True lilies are highly toxic to cats and can cause kidney failure. Do not put Lilium in a home with cats." },
      { q: "How do I stop lily pollen staining?", a: "Remove the anthers as each flower opens. If pollen lands on fabric, lift it with tape rather than rubbing." },
      { q: "Are white lilies only for funerals?", a: "No. They are common in sympathy work and Easter, but they also appear in weddings and formal celebrations. Culture and card wording matter." },
      { q: "How long do cut lilies last?", a: "A stem with several buds can look good for a week or more as flowers open in sequence." },
    ],
    sources: [
      { label: "ASPCA — Lily (Lilium)" },
      { label: "North Carolina State Extension / veterinary references on lily toxicity in cats" },
      { label: "Royal Horticultural Society — Lilium" },
    ],
    images: [
      unsplashImage("photo-1508610048659-a06b669e3321", "White lily with visible stamens", "white-lily-flower-close-up.jpg", "Annie Spratt", "hero"),
    ],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Lily Flower Guide: Types, Meaning, Care & Pet Safety | BlossomPot",
    seoDescription:
      "Learn the difference between true lilies and other 'lilies', plus meanings, seasons, care and why Lilium is dangerous for cats.",
    h1: "Lily: Types, Meaning, Care & Pet Safety",
  },
];
