import { unsplashImage } from "../images";
import type { FlowerGuide } from "../types";

const TEAM = "BlossomPot Editorial Team";
const UPDATED = "2026-08-16";

function guide(partial: FlowerGuide): FlowerGuide {
  return partial;
}

export const moreFlowerGuides: FlowerGuide[] = [
  guide({
    slug: "sunflower",
    name: "Sunflower",
    commonNames: ["Common sunflower"],
    botanicalName: "Helianthus annuus",
    family: "Asteraceae",
    letter: "S",
    shortDescription: "Tall, sunny bloom associated with loyalty and late-summer gifts.",
    glance:
      "The common sunflower (Helianthus annuus) is an annual in the daisy family, grown for its large composite flower heads. Cut sunflowers are a late-summer favourite and are also produced as a commercial crop beyond the backyard season. They are widely associated with loyalty, warmth and celebration rather than formal romance.",
    whatIs:
      "A sunflower head is a composite of many tiny florets surrounded by yellow ray florets. Florists sell branching spray types as well as large single heads.",
    about: [
      "Sunflowers are native to North America and were domesticated for seed long before they became ornamental cut flowers. Commercial breeding now includes pollen-less cultivars that last longer in the vase and shed less mess.",
      "Outdoor gardens in the Northern Hemisphere typically flower from midsummer into autumn. Florists can source stems for more of the year from greenhouse and import channels, but the flower still feels seasonal — people expect sunflowers in warm months.",
      "They suit birthdays, thank-yous and congratulations because they read cheerful and informal. Large heads need sturdy wrapping and a heavy vase.",
    ],
    meaning: [
      "Modern Western gifting links sunflowers with adoration, loyalty and positivity. In some East Asian contexts they can also signal lasting regard.",
      "They are rarely used as a primary funeral flower in Western practice, though bright mixed sympathy pieces sometimes include them if the family asks for a celebration-of-life palette.",
    ],
    colours: [
      { colour: "yellow", label: "Golden yellow", association: "Warmth, loyalty and cheer", occasions: ["birthday", "congratulations", "thank-you"] },
      { colour: "orange", label: "Orange / rust", association: "Autumn palettes and richer celebration tones", occasions: ["just-because"] },
    ],
    varieties: [
      { name: "Large-headed types", summary: "Single dramatic heads on thick stems; need support." },
      { name: "Spray / branching types", summary: "Several smaller heads; easier in mixed bouquets." },
      { name: "Pollen-less cultivars", summary: "Bred for cut-flower use; less shedding on tabletops." },
    ],
    season: ["summer", "autumn"],
    seasonSummary: "Peak garden and florist character is summer into early autumn; some commercial supply exists outside that window.",
    seasonDetail: [
      "In the US, Canada, the UK and northern Europe, sunflowers feel 'in season' from roughly July to October.",
      "Australia's local season sits in the opposite warm months. Imports can appear at other times but may cost more.",
    ],
    marketNotes: [
      { market: "us", summary: "A late-summer staple and a frequent birthday flower." },
      { market: "uk", summary: "Popular in late summer mixed bunches; British field sunflowers are seasonal." },
      { market: "australia", summary: "Local warm-season crop; imports fill cooler months." },
      { market: "canada", summary: "Short, bright late-summer window in most provinces." },
      { market: "europe", summary: "Field and greenhouse production through the warm months." },
      { market: "uae", summary: "Imported; handle quickly in summer heat." },
    ],
    origin: "North America.",
    habitat: "Open, sunny fields and gardens.",
    appearance: "Large composite heads with yellow rays and a brown or green disc; coarse, hairy stems.",
    fragrance: "Usually none to very light.",
    vaseLife: "Often around a week for fresh, well-conditioned stems; large heads drink a lot of water.",
    cutFlower: true,
    bouquetUse: "Solo bunches or mixed with seasonal foliage and russet tones.",
    floristUses: "Birthday, get-well, harvest and informal congratulations designs.",
    care: [
      "Use a heavy vase and recut the thick stems.",
      "Change water frequently; sunflower stems foul water quickly.",
      "Keep out of direct midday sun after delivery — they already look like summer.",
    ],
    occasions: ["birthday", "congratulations", "thank-you", "just-because", "get-well"],
    occasionNotes: ["Choose sunflowers when you want warmth without formal romance."],
    petSafety: "Helianthus is generally considered non-toxic, but any plant material can cause stomach upset if eaten. Confirm if a specific cultivar or dye is involved.",
    pollenNotes: "Traditional types shed pollen; ask for pollen-less cut cultivars if tabletops matter.",
    facts: ["Sunflower heads track the sun while in bud (heliotropism); mature cut heads do not keep doing this in a vase."],
    relatedFlowers: ["gerbera", "chrysanthemum", "dahlia", "rose"],
    relatedColours: ["yellow", "orange"],
    relatedOccasions: ["birthday", "congratulations", "thank-you"],
    shopQuery: "sunflower",
    shopCategory: "flowers",
    faqs: [
      { q: "When are sunflowers in season?", a: "They feel most seasonal in summer and early autumn. Some commercial stems are available at other times." },
      { q: "Do sunflowers make a good birthday gift?", a: "Yes. They read cheerful and informal, which suits many birthday relationships." },
      { q: "How long do cut sunflowers last?", a: "Often around a week with clean water and a sturdy vase. They are thirsty." },
    ],
    sources: [{ label: "USDA / North American ethnobotany of Helianthus" }, { label: "Royal Horticultural Society — Helianthus" }],
    images: [unsplashImage("photo-1597848212624-e593b1d6c0d6", "Yellow sunflower facing the light", "yellow-sunflower-close-up.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Sunflower Guide: Meaning, Season & Care | BlossomPot",
    seoDescription: "Learn sunflower meanings, seasonality and vase care. See when sunflowers make the best birthday and congratulations gifts.",
    h1: "Sunflower: Meaning, Season & Care Guide",
  }),
  guide({
    slug: "hydrangea",
    name: "Hydrangea",
    commonNames: ["Mophead hydrangea", "Lacecap hydrangea"],
    botanicalName: "Hydrangea macrophylla (most cut types)",
    family: "Hydrangeaceae",
    letter: "H",
    shortDescription: "Large clustered heads used in weddings and statement bouquets.",
    glance:
      "Hydrangeas are shrubs grown for large flower heads made of many small florets. Cut hydrangeas are popular in weddings because one stem fills space. They wilt quickly if under-hydrated. Flower colour in the garden can shift with soil chemistry; florist colours are usually set by cultivar and grower practice.",
    whatIs:
      "Most florist hydrangeas are Hydrangea macrophylla mopheads or lacecaps. The showy parts are often sterile florets surrounding smaller fertile flowers.",
    about: [
      "Hydrangeas are native to Asia and the Americas. Macrophylla types are the familiar mopheads of temperate gardens. Panicle hydrangeas (H. paniculata) flower later and are more often a garden than a cut-florist crop.",
      "Garden mophead colour can be blue, purple or pink depending on aluminium availability and soil pH — a well-documented horticultural effect. A cut stem from a florist, however, will not change colour in your vase.",
      "Cut hydrangeas are available for much of the year from specialist growers, with a natural flush in late spring and summer in many northern gardens. They are thirsty and are often conditioned by recutting and, in professional work, sometimes submerged briefly to revive limp heads.",
    ],
    meaning: [
      "Modern florist language often links hydrangeas with gratitude, understanding and heartfelt emotion. Older European lists were less flattering in places — another reason not to treat flower dictionaries as universal.",
      "White hydrangeas are a wedding staple. Antique greens and blush tones are popular in garden-style events.",
    ],
    colours: [
      { colour: "blue", label: "Blue", association: "Calm apology or heartfelt thanks in modern use", occasions: ["thank-you", "wedding"] },
      { colour: "pink", label: "Pink", association: "Romance and celebration", occasions: ["wedding", "mothers-day"] },
      { colour: "white", label: "White", association: "Grace and formality", occasions: ["wedding", "sympathy"] },
      { colour: "green", label: "Antique green", association: "Modern garden palettes", occasions: ["wedding", "housewarming"] },
      { colour: "purple", label: "Purple", association: "Abundance and uniqueness", occasions: ["congratulations"] },
    ],
    varieties: [
      { name: "Mophead", summary: "Rounded heads; the main wedding and bouquet type." },
      { name: "Lacecap", summary: "Flat heads with a lace-like ring of sterile florets." },
    ],
    season: ["spring", "summer", "autumn"],
    seasonSummary: "Garden flush is late spring–summer; commercial cuts extend availability.",
    seasonDetail: [
      "Northern gardens typically show mopheads from early summer, with some colouring into autumn.",
      "Dried hydrangeas are a separate craft product and should not be confused with fresh cut stems.",
    ],
    marketNotes: [
      { market: "us", summary: "A major wedding flower from late spring through autumn events." },
      { market: "uk", summary: "Classic British garden shrub; British-grown stems are seasonal, imports fill gaps." },
      { market: "australia", summary: "Local season follows the Southern Hemisphere summer." },
      { market: "canada", summary: "Summer garden shrub; florist stems often imported outside the local flush." },
      { market: "europe", summary: "Strong garden culture and commercial cut production in milder regions." },
      { market: "uae", summary: "Imported luxury stem; hydration after delivery is critical in dry indoor air." },
    ],
    origin: "Asia and the Americas, depending on species.",
    habitat: "Woodland-edge gardens; they prefer consistent moisture.",
    appearance: "Large clustered heads on woody or semi-woody stems.",
    fragrance: "Usually none.",
    vaseLife: "Variable. Well-conditioned stems can last several days to over a week; limp heads often signal a hydration problem rather than the end of life.",
    cutFlower: true,
    bouquetUse: "Volume flower in wedding and statement designs.",
    floristUses: "Arches, centrepieces, thank-you bouquets, housewarming arrangements.",
    care: [
      "Recut stems and place in deep water immediately.",
      "If a head wilts, recut under water and leave the stem in a cool, deep vase; professionals sometimes dunk the head briefly in water.",
      "Mist can help in dry rooms, but clean vase water matters more.",
      "Keep away from heat vents.",
    ],
    occasions: ["wedding", "thank-you", "mothers-day", "housewarming", "sympathy"],
    occasionNotes: ["One hydrangea stem can replace several smaller flowers when you need visual mass."],
    petSafety: "Hydrangeas contain cyanogenic glycosides and are listed as toxic if ingested. Keep chewed stems away from pets and children.",
    pollenNotes: "Generally modest compared with lilies.",
    facts: ["Garden mophead colour change is about aluminium uptake, not a dye poured into the vase."],
    relatedFlowers: ["peony", "rose", "lisianthus", "gardenia"],
    relatedColours: ["blue", "pink", "white", "green"],
    relatedOccasions: ["wedding", "thank-you", "mothers-day"],
    relatedCareSlug: "how-to-care-for-hydrangeas",
    shopQuery: "hydrangea",
    shopCategory: "flowers",
    faqs: [
      { q: "Why did my hydrangea wilt overnight?", a: "Cut hydrangeas wilt quickly if the stem cannot take up water. Recut the stem and use a deep, clean vase." },
      { q: "Can I change hydrangea colour in the vase?", a: "No. Garden soil chemistry can influence growing plants; a cut florist stem keeps the colour it was harvested with." },
      { q: "Are hydrangeas good wedding flowers?", a: "Yes, especially when you need volume. They need careful hydration on the day." },
    ],
    sources: [{ label: "Royal Horticultural Society — Hydrangea" }, { label: "ASPCA — Hydrangea" }],
    images: [unsplashImage("photo-1599733594230-6b5631bdc1e0", "Blue hydrangea flower head", "blue-hydrangea-flower-close-up.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Hydrangea Guide: Colours, Meaning & Care | BlossomPot",
    seoDescription: "Learn why hydrangeas wilt, how garden colour works, and when hydrangeas suit weddings and thank-you gifts.",
    h1: "Hydrangea: Colours, Meaning & Care Guide",
  }),
  guide({
    slug: "carnation",
    name: "Carnation",
    commonNames: ["Clove pink", "Dianthus caryophyllus"],
    botanicalName: "Dianthus caryophyllus",
    family: "Caryophyllaceae",
    letter: "C",
    shortDescription: "Ruffled, long-lasting florist staple with colour-specific meanings.",
    glance:
      "Carnations (Dianthus caryophyllus) are among the world's most produced cut flowers. They last well, take dye and wire easily, and have a long history in Mother's Day and sympathy work. Colour meanings are traditional, not scientific. Fragrance is clove-like in many cultivars.",
    whatIs:
      "A carnation is a herbaceous perennial grown as an annual cut-flower crop. Florist types include standards (one large bloom) and sprays (several smaller blooms).",
    about: [
      "Carnations have been cultivated for more than two thousand years around the Mediterranean. They remain a volume crop because they ship well and have a long vase life compared with many garden flowers.",
      "That reliability sometimes gives them an unfair 'cheap' reputation. Designers still use them for texture, colour and lasting power — especially in sympathy pieces and wired work.",
      "They are available year-round from greenhouse producers.",
    ],
    meaning: [
      "In the United States, pink carnations are strongly tied to Mother's Day, following early twentieth-century campaign history. White carnations have been used for remembrance of mothers who have died; red for living mothers. Those conventions are US-centred.",
      "Elsewhere, carnations appear in labour-day and political history (for example Portugal's Carnation Revolution) and in general affection. Do not assume one national story applies everywhere.",
    ],
    colours: [
      { colour: "pink", label: "Pink", association: "Gratitude and, in US tradition, Mother's Day", occasions: ["mothers-day", "thank-you"] },
      { colour: "red", label: "Red", association: "Admiration and deeper affection", occasions: ["romantic", "mothers-day"] },
      { colour: "white", label: "White", association: "Remembrance and pure affection", occasions: ["sympathy", "funeral"] },
      { colour: "yellow", label: "Yellow", association: "Disappointment in some older lists; cheer in modern mixed bunches", occasions: ["just-because"] },
    ],
    varieties: [
      { name: "Standard carnations", summary: "One large ruffled bloom per stem." },
      { name: "Spray carnations", summary: "Several smaller blooms; useful fillers." },
    ],
    season: ["year-round"],
    seasonSummary: "A year-round commercial cut flower.",
    seasonDetail: ["There is no meaningful 'out of season' for florist carnations in major markets."],
    marketNotes: [
      { market: "us", summary: "Especially visible around US Mother's Day." },
      { market: "uk", summary: "Everyday florist staple; less exclusively a Mother's Day emblem than in the US." },
      { market: "europe", summary: "Major production and everyday mixed-bouquet use." },
      { market: "canada", summary: "Year-round staple with a US-style Mother's Day association in May." },
      { market: "australia", summary: "Year-round import and local greenhouse supply." },
      { market: "uae", summary: "Common imported cut flower; handles transport well." },
    ],
    origin: "Mediterranean basin.",
    habitat: "Commercial greenhouses; also cottage gardens.",
    appearance: "Ruffled petals on jointed, bluish-green stems.",
    fragrance: "Often a distinctive clove-like scent; intensity varies.",
    vaseLife: "Frequently more than a week with clean water — one of the longer-lasting common cuts.",
    cutFlower: true,
    bouquetUse: "Fillers, sympathy sprays, Mother's Day bunches, and colourful mixed designs.",
    floristUses: "Wired boutonnieres, funeral work, and long-lasting grocery bunches.",
    care: [
      "Recut above a node if the stem is woody at the base.",
      "Remove foliage below water.",
      "They tolerate cooler rooms well.",
    ],
    occasions: ["mothers-day", "birthday", "sympathy", "thank-you", "funeral"],
    occasionNotes: ["In the US, confirm whether pink or mixed carnations match the family's Mother's Day tradition."],
    petSafety: "Dianthus species can cause mild gastrointestinal upset if eaten; they are not in the same emergency category as true lilies for cats.",
    pollenNotes: "Generally low-drama; fragrance is the more common sensitivity.",
    facts: ["Carnations take floral dye readily, which is why 'blue carnations' in shops are usually tinted."],
    relatedFlowers: ["rose", "alstroemeria", "chrysanthemum", "lisianthus"],
    relatedColours: ["pink", "red", "white"],
    relatedOccasions: ["mothers-day", "sympathy", "thank-you"],
    shopQuery: "carnation",
    shopCategory: "flowers",
    faqs: [
      { q: "Why are carnations used for Mother's Day?", a: "In the US, early Mother's Day campaigns used carnations. Pink and red/white conventions grew from that history and are not worldwide rules." },
      { q: "How long do carnations last?", a: "They are among the longer-lasting everyday cut flowers when water stays clean." },
      { q: "Are blue carnations natural?", a: "True blue is not a natural carnation colour; shop 'blue' stems are typically dyed." },
    ],
    sources: [{ label: "Society of American Florists — carnation history" }, { label: "RHS — Dianthus" }],
    images: [unsplashImage("photo-1468327768560-75b778cbb551", "Pink carnation petals", "pink-carnation-flower.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Carnation Guide: Meaning, Colours & Mother's Day | BlossomPot",
    seoDescription: "Understand carnation colours, vase life and the US Mother's Day tradition — and when carnations suit sympathy or everyday gifts.",
    h1: "Carnation: Meaning, Colours & Care Guide",
  }),
  guide({
    slug: "gerbera",
    name: "Gerbera",
    commonNames: ["Gerbera daisy", "Transvaal daisy"],
    botanicalName: "Gerbera jamesonii hybrids",
    family: "Asteraceae",
    letter: "G",
    shortDescription: "Cheerful daisy-form cut flower in a wide colour range.",
    glance:
      "Gerberas are hybrid daisies grown as colourful cut flowers. They are associated with cheerfulness and are common birthday and get-well flowers. Hollow stems need careful support. They are produced year-round in greenhouses.",
    whatIs:
      "Gerbera jamesonii and its hybrids are native to southern Africa and are now a global greenhouse crop.",
    about: [
      "A gerbera 'flower' is a composite head. Breeders have produced standard large heads and smaller mini gerberas in almost every colour except true blue.",
      "They photograph brightly and feel informal, which is why they appear in birthday and congratulations work more than in formal sympathy (unless requested).",
    ],
    meaning: [
      "Modern lists usually assign gerberas cheerfulness, innocence and everyday joy. There is less historical floriography than for roses.",
    ],
    colours: [
      { colour: "pink", label: "Pink", association: "Admiration and celebration", occasions: ["birthday"] },
      { colour: "orange", label: "Orange", association: "Energy", occasions: ["congratulations"] },
      { colour: "yellow", label: "Yellow", association: "Sunshine and get-well wishes", occasions: ["get-well"] },
      { colour: "red", label: "Red", association: "Bolder affection without rose formality", occasions: ["just-because"] },
      { colour: "white", label: "White", association: "Purity and simplicity", occasions: ["thank-you"] },
    ],
    varieties: [
      { name: "Standard gerbera", summary: "Large single heads on long stems." },
      { name: "Mini gerbera", summary: "Smaller heads for mixed bouquets." },
    ],
    season: ["year-round"],
    seasonSummary: "Greenhouse crop; available all year.",
    seasonDetail: ["Quality depends more on handling than on outdoor season. Bent necks usually mean a hydration or support issue."],
    marketNotes: [
      { market: "us", summary: "Year-round grocery and florist colour flower." },
      { market: "uk", summary: "Everyday cheerful cut flower." },
      { market: "australia", summary: "Year-round greenhouse and import supply." },
      { market: "canada", summary: "Year-round greenhouse colour flower." },
      { market: "europe", summary: "Major Dutch and southern European greenhouse crop." },
      { market: "uae", summary: "Imported; keep cool after delivery." },
    ],
    origin: "Southern Africa (species); hybrids worldwide.",
    habitat: "Commercial greenhouses.",
    appearance: "Daisy-form heads on leafless, hollow stems.",
    fragrance: "None to very light.",
    vaseLife: "Several days to about a week; necks bend if water uptake fails.",
    cutFlower: true,
    bouquetUse: "Colour blocks and birthday mixed bunches.",
    floristUses: "Get-well, birthday, children's celebrations, modern monochrome vases.",
    care: [
      "Keep water shallow-to-moderate and very clean — hollow stems rot if bacteria build up.",
      "Support the neck; a grid or wrapped bunch helps.",
      "Avoid deep submersion of the head.",
    ],
    occasions: ["birthday", "get-well", "congratulations", "just-because"],
    occasionNotes: ["Gerberas are a safe cheerful choice when roses would feel too romantic."],
    petSafety: "Generally regarded as non-toxic, but chewing can still cause mild upset.",
    pollenNotes: "Some people sensitive to daisy-family pollen may notice it; many cut cultivars are selected for cleaner centres.",
    facts: ["Gerberas were named for German naturalist Traugott Gerber."],
    relatedFlowers: ["sunflower", "chrysanthemum", "rose", "alstroemeria"],
    relatedColours: ["pink", "orange", "yellow"],
    relatedOccasions: ["birthday", "get-well"],
    shopQuery: "gerbera",
    shopCategory: "flowers",
    faqs: [
      { q: "Why do gerbera stems bend?", a: "The stems are hollow and collapse when bacteria block water or when the head is too heavy for a weak stem." },
      { q: "Are gerberas good for get-well gifts?", a: "Yes. Bright, informal colour is the usual reason they are chosen." },
    ],
    sources: [{ label: "RHS — Gerbera" }],
    images: [unsplashImage("photo-1508610048659-a06b669e3321", "Orange gerbera daisy", "orange-gerbera-daisy-flower.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Gerbera Daisy Guide: Colours, Meaning & Care | BlossomPot",
    seoDescription: "Learn why gerberas suit birthdays and get-well gifts, and how to stop hollow stems from bending in the vase.",
    h1: "Gerbera: Colours, Meaning & Care Guide",
  }),
  guide({
    slug: "chrysanthemum",
    name: "Chrysanthemum",
    commonNames: ["Mum", "Florist chrysanthemum"],
    botanicalName: "Chrysanthemum × morifolium",
    family: "Asteraceae",
    letter: "C",
    shortDescription: "Autumn florist favourite with many forms and cultural meanings.",
    glance:
      "Florist chrysanthemums are long-lasting composite flowers with many forms — sprays, disbuds, spiders and pompoms. In the US they often signal autumn and cheer. In several European and East Asian contexts white chrysanthemums are funeral flowers. Know the recipient's culture before sending white mums as a casual gift.",
    whatIs:
      "Modern florist mums are complex hybrids grown as short-day greenhouse crops so they can be produced beyond autumn.",
    about: [
      "Chrysanthemums were first cultivated in China and are the imperial flower of Japan. They reached Europe centuries later and became a florist volume crop because they last.",
      "Garden hardy mums flower in autumn. Florist mums are available much of the year because growers control day length.",
    ],
    meaning: [
      "Symbolism splits sharply by culture. In the US, mums can mean friendship, joy or autumn football-season cheer. In countries such as France, Italy and some others, chrysanthemums — especially white — are strongly associated with graves and All Saints' commemorations.",
      "In Japan the chrysanthemum is a noble emblem. Always prefer the recipient's tradition over a generic 'flower meaning' list.",
    ],
    colours: [
      { colour: "yellow", label: "Yellow", association: "Optimism in many Western casual gifts", occasions: ["birthday", "get-well"] },
      { colour: "white", label: "White", association: "In some cultures, mourning — ask before gifting", occasions: ["sympathy"] },
      { colour: "pink", label: "Pink", association: "Gentler celebration", occasions: ["thank-you"] },
      { colour: "red", label: "Red", association: "Love or well-wishing depending on culture", occasions: ["just-because"] },
    ],
    varieties: [
      { name: "Spray chrysanthemums", summary: "Many small blooms; the everyday mixed-bouquet mum." },
      { name: "Disbud / standard", summary: "One large bloom per stem." },
      { name: "Spider and novelty forms", summary: "Unusual petal shapes for contemporary design." },
    ],
    season: ["autumn", "year-round"],
    seasonSummary: "Garden association is autumn; commercial supply is year-round.",
    seasonDetail: ["Short-day lighting control lets growers flower mums on a schedule."],
    marketNotes: [
      { market: "us", summary: "Football-season and Thanksgiving colour; also a year-round filler." },
      { market: "europe", summary: "In several countries, avoid casual white mum gifts around All Saints' / memorial dates." },
      { market: "uk", summary: "Common florist filler; funeral association exists but is weaker than in some continental countries." },
      { market: "canada", summary: "Autumn garden plant and year-round florist filler." },
      { market: "australia", summary: "Mother's Day in May is autumn there — mums are a traditional Australian Mother's Day flower." },
      { market: "uae", summary: "Imported long-lasting filler." },
    ],
    origin: "East Asia.",
    habitat: "Gardens and greenhouses.",
    appearance: "Composite heads in many petal forms.",
    fragrance: "Herbal to light; some people dislike the foliage scent.",
    vaseLife: "Often well over a week — among the longest common cuts.",
    cutFlower: true,
    bouquetUse: "Fillers and autumn-themed designs.",
    floristUses: "Sympathy (culture-dependent), celebrations, long-lasting mixed bouquets.",
    care: ["Recut woody stems, strip underwater foliage, and they are relatively forgiving."],
    occasions: ["birthday", "sympathy", "congratulations", "just-because", "mothers-day"],
    occasionNotes: ["In Australia, chrysanthemums are a traditional Mother's Day flower because May is autumn."],
    petSafety: "Chrysanthemums contain compounds that can irritate pets if ingested; they are listed as toxic by the ASPCA.",
    pollenNotes: "Daisy-family pollen can bother some allergy sufferers; decorative double forms vary.",
    facts: ["The name means 'golden flower' in Greek, reflecting early yellow types."],
    relatedFlowers: ["alstroemeria", "carnation", "gerbera", "dahlia"],
    relatedColours: ["yellow", "white", "pink"],
    relatedOccasions: ["birthday", "sympathy"],
    shopQuery: "chrysanthemum",
    shopCategory: "flowers",
    faqs: [
      { q: "Are chrysanthemums funeral flowers?", a: "In some European and East Asian contexts, yes — especially white. In the US they are often casual or autumnal. Check culture before sending." },
      { q: "Why are mums a Mother's Day flower in Australia?", a: "Australian Mother's Day is in May, which is autumn, when chrysanthemums naturally flower." },
    ],
    sources: [{ label: "RHS — Chrysanthemum" }, { label: "ASPCA — Chrysanthemum" }],
    images: [unsplashImage("photo-1508610048659-a06b669e3321", "Yellow chrysanthemum bloom", "yellow-chrysanthemum-flower.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Chrysanthemum Guide: Meaning, Culture & Care | BlossomPot",
    seoDescription: "Learn chrysanthemum meanings across cultures, autumn seasonality and why white mums are not a casual gift everywhere.",
    h1: "Chrysanthemum: Meaning, Culture & Care Guide",
  }),
];
