import { unsplashImage } from "../images";
import type { FlowerGuide } from "../types";

const TEAM = "BlossomPot Editorial Team";
const UPDATED = "2026-08-16";

function g(partial: FlowerGuide): FlowerGuide {
  return partial;
}

const sharedMarketsYearRound = [
  { market: "us" as const, summary: "Year-round commercial supply through imports and greenhouses." },
  { market: "canada" as const, summary: "Year-round florist supply; outdoor garden season is shorter." },
  { market: "uk" as const, summary: "Everyday imported florist flower; British garden season is separate." },
  { market: "europe" as const, summary: "Strong Dutch auction and greenhouse distribution." },
  { market: "australia" as const, summary: "Local season plus imports from the opposite hemisphere." },
  { market: "uae" as const, summary: "Imported; protect from heat after delivery." },
];

export const specialtyFlowerGuides: FlowerGuide[] = [
  g({
    slug: "alstroemeria",
    name: "Alstroemeria",
    commonNames: ["Peruvian lily", "Lily of the Incas"],
    botanicalName: "Alstroemeria",
    family: "Alstroemeriaceae",
    letter: "A",
    shortDescription: "Long-lasting Peruvian lily used in mixed bouquets.",
    glance:
      "Alstroemeria, often called Peruvian lily, is a South American genus grown as a long-lasting cut flower. Twisted leaves and speckled inner tepals are typical. It is a workhorse mixed-bouquet flower rather than a formal romantic emblem. Related to true lilies in look only — it is a different family, but it is still not a cat-safe substitute for Lilium without checking current toxicity advice.",
    whatIs:
      "Alstroemeria is a tuberous perennial from South America, bred into many cut-flower colours.",
    about: [
      "Commercial alstroemeria is produced year-round in greenhouses. Each stem carries several florets that open in sequence, which is why bunches last.",
      "Florists use it as a filler-hero: cheaper than roses, more colourful than ruscus, and reliable in mixed birthday designs.",
    ],
    meaning: [
      "Modern florist copy often assigns friendship, devotion and wealth. Those meanings are marketing conventions more than deep historical floriography.",
    ],
    colours: [
      { colour: "pink", label: "Pink", association: "Friendship and gentle celebration", occasions: ["birthday", "thank-you"] },
      { colour: "orange", label: "Orange", association: "Energy", occasions: ["congratulations"] },
      { colour: "white", label: "White", association: "Support and mixed sympathy palettes", occasions: ["get-well"] },
      { colour: "purple", label: "Purple", association: "Admiration", occasions: ["just-because"] },
    ],
    varieties: [{ name: "Cut-flower hybrids", summary: "Bred for stem length, colour and multiple florets per stem." }],
    season: ["spring", "summer", "year-round"],
    seasonSummary: "Year-round commercial cut flower.",
    seasonDetail: ["Garden plants may have a warmer-month flush; shops do not depend on that."],
    marketNotes: sharedMarketsYearRound,
    origin: "South America, especially Chile and Brazil depending on species.",
    habitat: "Cool greenhouse production and mild gardens.",
    appearance: "Clusters of lily-like flowers with patterned inner tepals; leaves often twist on the stem.",
    fragrance: "Usually light or none.",
    vaseLife: "Often well over a week as florets open in turn.",
    cutFlower: true,
    bouquetUse: "Mixed birthday and everyday bouquets.",
    floristUses: "Volume colour in supermarket and florist mixed bunches.",
    care: ["Recut stems, remove submerged leaves, and they are relatively easy. Individual florets can be pinched when spent."],
    occasions: ["birthday", "thank-you", "congratulations", "just-because"],
    occasionNotes: ["A practical long-lasting choice when you want colour without a rose message."],
    petSafety:
      "Alstroemeria is a different genus from true lilies. Some sources report milder irritation if ingested; it is not a documented cat kidney-failure lily. Still keep chewed stems away from pets and never assume 'lily' in the common name means safe.",
    pollenNotes: "Usually modest compared with Oriental lilies.",
    facts: ["The leaves twist so the underside faces up — a botanical quirk used in identification."],
    relatedFlowers: ["lily", "rose", "gerbera", "lisianthus"],
    relatedColours: ["pink", "orange", "white"],
    relatedOccasions: ["birthday", "thank-you"],
    shopQuery: "alstroemeria",
    shopCategory: "flowers",
    faqs: [
      { q: "Is alstroemeria a true lily?", a: "No. It is nicknamed Peruvian lily but belongs to a different family from Lilium." },
      { q: "How long does alstroemeria last?", a: "It is one of the longer-lasting mixed-bouquet flowers when water stays clean." },
    ],
    sources: [{ label: "RHS — Alstroemeria" }],
    images: [unsplashImage("photo-1468327768560-75b778cbb551", "Pink alstroemeria blooms", "alstroemeria-pink-flowers.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Alstroemeria Guide: Meaning, Care & Vase Life | BlossomPot",
    seoDescription: "Learn what Peruvian lilies are, how long they last, and how they differ from true lilies in bouquets.",
    h1: "Alstroemeria: Meaning, Care & Bouquet Uses",
  }),
  g({
    slug: "babys-breath",
    name: "Baby's Breath",
    commonNames: ["Gypsophila", "Gyp"],
    botanicalName: "Gypsophila paniculata",
    family: "Caryophyllaceae",
    letter: "B",
    shortDescription: "Airy filler flower used in bouquets and wedding work.",
    glance:
      "Baby's breath (Gypsophila) is a cloud of tiny white or tinted flowers used as a filler and, increasingly, as a solo bouquet. It is associated with innocence and everlasting love in modern wedding marketing. Dried and fresh forms are both common. It is generally available year-round as a commercial cut.",
    whatIs:
      "Gypsophila paniculata is a perennial grown for highly branched sprays of small flowers.",
    about: [
      "For decades baby's breath was the default filler around roses. Designers now also use it alone for a soft, informal look.",
      "It dries well, which is why it appears in keepsake bunches. Fresh stems still need clean water; they are not maintenance-free.",
    ],
    meaning: [
      "Modern wedding language links gypsophila with everlasting love, purity and innocence. Those readings are contemporary conventions.",
    ],
    colours: [
      { colour: "white", label: "White", association: "Innocence and wedding softness", occasions: ["wedding", "new-baby", "sympathy"] },
      { colour: "pink", label: "Tinted pink", association: "Playful romance; often dyed", occasions: ["romantic"] },
    ],
    varieties: [
      { name: "Million Star and similar", summary: "Dense commercial selections used by florists." },
      { name: "Dried gypsophila", summary: "Preserved for lasting décor; texture differs from fresh." },
    ],
    season: ["year-round"],
    seasonSummary: "Year-round commercial filler.",
    seasonDetail: ["Garden gypsophila flowers in summer; shops do not wait for that."],
    marketNotes: sharedMarketsYearRound,
    origin: "Eurasia; now a global cut-flower crop.",
    habitat: "Well-drained soils in nature; greenhouse and field production commercially.",
    appearance: "Airy sprays of tiny five-petalled flowers.",
    fragrance: "Light, slightly sweet or herbal.",
    vaseLife: "Fresh stems often last well over a week; dried stems last months.",
    cutFlower: true,
    bouquetUse: "Filler or solo cloud bouquet.",
    floristUses: "Weddings, baby gifts, sympathy softness, dried décor.",
    care: ["Recut, use clean water, and keep the cloud away from crushing. Remove slimy stem ends if water sours."],
    occasions: ["wedding", "new-baby", "romantic", "sympathy"],
    occasionNotes: ["A baby's breath cloud can feel more 'new baby' than a formal rose dozen."],
    petSafety: "Gypsophila can cause mild stomach upset if eaten; not in the true-lily emergency class.",
    pollenNotes: "Usually low compared with lilies; dried dust can bother some people.",
    facts: ["The botanical name refers to the plant's preference for gypsum-rich, alkaline soils."],
    relatedFlowers: ["rose", "lisianthus", "statice", "queen-annes-lace"],
    relatedColours: ["white", "pink"],
    relatedOccasions: ["wedding", "new-baby"],
    shopQuery: "baby breath",
    shopCategory: "flower-bouquets",
    faqs: [
      { q: "Is baby's breath only a filler?", a: "No. It is still used around other flowers, but solo gypsophila bouquets are now common." },
      { q: "Does baby's breath last?", a: "Fresh stems last well; dried stems last much longer as décor." },
    ],
    sources: [{ label: "RHS — Gypsophila" }],
    images: [unsplashImage("photo-1468327768560-75b778cbb551", "White baby's breath in a loose bouquet", "babys-breath-white-bouquet.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Baby's Breath Guide: Meaning & Wedding Uses | BlossomPot",
    seoDescription: "Learn what gypsophila is, why it appears in weddings, and how fresh baby's breath differs from dried.",
    h1: "Baby's Breath: Meaning, Uses & Care",
  }),
  g({
    slug: "calla-lily",
    name: "Calla Lily",
    commonNames: ["Arum lily", "Zantedeschia"],
    botanicalName: "Zantedeschia",
    family: "Araceae",
    letter: "C",
    shortDescription: "Sculptural spathe flower used in weddings and formal designs.",
    glance:
      "Calla lilies are not true lilies. They are aroid plants (Zantedeschia) whose 'flower' is a spathe around a spadix. White callas are associated with formality, weddings and sometimes sympathy. Coloured callas are modern and sculptural. All parts are irritating if chewed, and they are not a cat-safe Lilium alternative in the sense of being edible — they are simply a different toxin profile.",
    whatIs:
      "Zantedeschia species from southern Africa, grown as cut flowers and pot plants.",
    about: [
      "The elegant trumpet is a modified leaf (spathe), not a petal. That is why callas look architectural compared with roses.",
      "White Zantedeschia aethiopica is the classic large calla. Modern coloured miniatures come from other species and hybrids.",
    ],
    meaning: [
      "White callas are often linked with purity, rebirth and elegant sympathy. They appear in both bridal and funeral work — styling decides the tone.",
    ],
    colours: [
      { colour: "white", label: "White", association: "Formality, weddings and remembrance", occasions: ["wedding", "sympathy"] },
      { colour: "pink", label: "Pink", association: "Admiration", occasions: ["anniversary"] },
      { colour: "yellow", label: "Yellow", association: "Gratitude", occasions: ["thank-you"] },
      { colour: "purple", label: "Purple / black-red", association: "Modern drama", occasions: ["wedding"] },
    ],
    varieties: [
      { name: "Large white calla", summary: "Classic arum form used in formal designs." },
      { name: "Mini coloured callas", summary: "Shorter, saturated stems for contemporary bouquets." },
    ],
    season: ["spring", "summer", "year-round"],
    seasonSummary: "Commercial cuts are widely available; garden bloom is warmer months in frost-free or lifted-bulb climates.",
    seasonDetail: ["Treat shop availability as mostly year-round with quality peaks."],
    marketNotes: sharedMarketsYearRound,
    origin: "Southern Africa.",
    habitat: "Moist soils in nature; greenhouse cuts commercially.",
    appearance: "Smooth spathe wrapping a central spadix; leafless cut stems.",
    fragrance: "Usually light.",
    vaseLife: "Often around a week; avoid bruising the spathe.",
    cutFlower: true,
    bouquetUse: "Modern bridal and formal sympathy lines.",
    floristUses: "Sculptural bouquets, church work, contemporary corporate.",
    care: ["Recut, use clean water, and handle spathes gently — bruises show as transparent patches."],
    occasions: ["wedding", "sympathy", "congratulations"],
    occasionNotes: ["Callas read formal. They are a poor match for a playful kids' birthday."],
    petSafety:
      "Aroids contain calcium oxalate crystals that irritate mouth and gut. Not the same as Lilium kidney failure in cats, but still keep away from pets that chew plants.",
    pollenNotes: "Low compared with Oriental lilies.",
    facts: ["The plant is an aroid, related to anthurium and peace lily, not to Lilium."],
    relatedFlowers: ["lily", "orchid", "anthurium", "rose"],
    relatedColours: ["white", "pink", "yellow"],
    relatedOccasions: ["wedding", "sympathy"],
    shopQuery: "calla",
    shopCategory: "flowers",
    faqs: [
      { q: "Is a calla lily a true lily?", a: "No. It is Zantedeschia, an aroid. The name is traditional, not botanical." },
      { q: "Are callas only for funerals?", a: "No. White callas are also a classic wedding flower. The arrangement and card set the tone." },
    ],
    sources: [{ label: "RHS — Zantedeschia" }, { label: "ASPCA — Calla Lily" }],
    images: [unsplashImage("photo-1455659817273-f093b0cdc19e", "White calla lily spathes", "white-calla-lily-flowers.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Calla Lily Guide: Meaning, Wedding Uses & Care | BlossomPot",
    seoDescription: "Learn why calla lilies are not true lilies, plus meanings, colours and how to keep spathes unbruised.",
    h1: "Calla Lily: Meaning, Varieties & Care",
  }),
  g({
    slug: "dahlia",
    name: "Dahlia",
    commonNames: ["Garden dahlia"],
    botanicalName: "Dahlia",
    family: "Asteraceae",
    letter: "D",
    shortDescription: "Late-summer show flower prized for form and colour range.",
    glance:
      "Dahlias are tuberous plants from Mexico, bred into an enormous range of forms and colours. They are a late-summer and autumn cut flower. Vase life is moderate and they dislike heat. They are wedding-popular when the date falls in season, and they have little of the year-round supermarket presence of roses.",
    whatIs:
      "Dahlia hybrids grown from tubers, classified by the American Dahlia Society and similar bodies into forms such as decorative, cactus, pompon and waterlily.",
    about: [
      "Aztec cultivation predates European breeding. Nineteenth- and twentieth-century hybridising created the show bench diversity gardeners know.",
      "Cut dahlias are seasonal. Some storage and opposite-hemisphere product exists, but most people meet them in late summer.",
    ],
    meaning: [
      "Modern lists often assign dignity, inner strength and commitment. Treat that as optional poetry, not a required message.",
    ],
    colours: [
      { colour: "pink", label: "Pink", association: "Kindness and celebration", occasions: ["wedding", "birthday"] },
      { colour: "red", label: "Red", association: "Power and passion", occasions: ["romantic"] },
      { colour: "peach", label: "Peach", association: "Modern wedding palettes", occasions: ["wedding"] },
      { colour: "white", label: "White", association: "Focus and formality", occasions: ["wedding"] },
    ],
    varieties: [
      { name: "Decorative", summary: "Broad, formal petals; common in bouquets." },
      { name: "Cactus", summary: "Rolled, spiky petals." },
      { name: "Pompon / ball", summary: "Small, tight spheres for texture." },
    ],
    season: ["summer", "autumn"],
    seasonSummary: "A late-summer to autumn flower in the Northern Hemisphere.",
    seasonDetail: [
      "In the US, Canada, UK and northern Europe, expect dahlias from midsummer until frost.",
      "Australia's local season is the opposite warm half of the year.",
    ],
    marketNotes: [
      { market: "us", summary: "Peak late summer; a favourite for autumn weddings." },
      { market: "uk", summary: "Classic late-summer British garden and florist flower." },
      { market: "australia", summary: "Local warm-season crop." },
      { market: "canada", summary: "Shorter late-summer window before frost." },
      { market: "europe", summary: "Late-summer garden and cut-flower favourite." },
      { market: "uae", summary: "Imported in season; heat shortens vase life." },
    ],
    origin: "Mexico and Central America.",
    habitat: "Sunny gardens; lifted or mulched over cold winters.",
    appearance: "Composite flowers from tiny pompoms to dinner-plate decoratives.",
    fragrance: "Usually none.",
    vaseLife: "Often three to seven days; heat and bacteria shorten it quickly.",
    cutFlower: true,
    bouquetUse: "Seasonal wedding and statement garden bouquets.",
    floristUses: "Late-summer colour, editorial wedding work.",
    care: ["Harvest or buy when nearly open. Recut, use clean water, and keep cool. They are not long-haul supermarket flowers."],
    occasions: ["wedding", "birthday", "congratulations"],
    occasionNotes: ["If the wedding is in February in the US, dahlias will be imported or substituted."],
    petSafety: "Generally considered non-toxic, but confirm if pets chew plants.",
    pollenNotes: "Double forms shed less than singles.",
    facts: ["Dahlia is Mexico's national flower."],
    relatedFlowers: ["peony", "chrysanthemum", "sunflower", "ranunculus"],
    relatedColours: ["pink", "peach", "red"],
    relatedOccasions: ["wedding", "birthday"],
    shopQuery: "dahlia",
    shopCategory: "flowers",
    faqs: [
      { q: "When are dahlias in season?", a: "Late summer and autumn in the Northern Hemisphere. Local frost ends the garden season." },
      { q: "Do dahlias last as long as roses?", a: "Usually not. They are prized for form more than for long vase life." },
    ],
    sources: [{ label: "American Dahlia Society" }, { label: "RHS — Dahlia" }],
    images: [unsplashImage("photo-1561181286-d3fee7d55364", "Pink dahlia with layered petals", "pink-dahlia-flower-close-up.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Dahlia Guide: Season, Types & Care | BlossomPot",
    seoDescription: "Learn dahlia seasons, forms and vase care — and why they are a late-summer wedding flower.",
    h1: "Dahlia: Season, Types & Care Guide",
  }),
  g({
    slug: "freesia",
    name: "Freesia",
    commonNames: ["Freesia"],
    botanicalName: "Freesia",
    family: "Iridaceae",
    letter: "F",
    shortDescription: "Fragrant, funnel-shaped stems used in spring and wedding work.",
    glance:
      "Freesias are South African irids grown for fragrant, funnel-shaped flowers arranged along one side of the stem. They are a cool-season cut flower and a wedding favourite when scent is wanted without lily pollen. Commercial supply is strongest in winter and spring in the north.",
    whatIs:
      "A cormous plant in the iris family, bred for cut-flower scent and colour.",
    about: [
      "Freesias became a European florist crop in the late nineteenth and twentieth centuries because of their perfume.",
      "Stems are delicate. They suit posies and wired work more than heavy mixed grocery bunches.",
    ],
    meaning: [
      "Modern lists often assign trust, thoughtfulness and innocence. Use them when you want fragrance and freshness more than a coded message.",
    ],
    colours: [
      { colour: "white", label: "White", association: "Trust and wedding freshness", occasions: ["wedding", "thank-you"] },
      { colour: "yellow", label: "Yellow", association: "Joy", occasions: ["birthday"] },
      { colour: "pink", label: "Pink", association: "Gentleness", occasions: ["anniversary"] },
      { colour: "purple", label: "Purple", association: "Calm admiration", occasions: ["thank-you"] },
    ],
    varieties: [{ name: "Single and double florist types", summary: "Doubles have more petals; scent still varies by cultivar." }],
    season: ["spring", "winter"],
    seasonSummary: "Cool-season commercial flower.",
    seasonDetail: ["Peak northern supply is winter–spring. Heat shortens vase life."],
    marketNotes: [
      { market: "us", summary: "A late-winter and spring scented stem." },
      { market: "uk", summary: "Classic British spring and wedding scent flower." },
      { market: "europe", summary: "Major cool-season greenhouse crop." },
      { market: "canada", summary: "Imported cool-season scented stem." },
      { market: "australia", summary: "Local cool-season window plus imports." },
      { market: "uae", summary: "Imported; keep in cool indoor air." },
    ],
    origin: "Southern Africa.",
    habitat: "Winter-rainfall climates; greenhouses commercially.",
    appearance: "Tubular flowers in a one-sided spike.",
    fragrance: "Often strong and sweet; a main reason to buy them.",
    vaseLife: "Moderate — several days to about a week, bud by bud.",
    cutFlower: true,
    bouquetUse: "Scented wedding and spring posies.",
    floristUses: "Bridal work, thank-you bunches, fragrance-focused designs.",
    care: ["Recut gently, keep cool, and let buds open in sequence. Avoid crushing the spike."],
    occasions: ["wedding", "thank-you", "anniversary"],
    occasionNotes: ["Choose freesia when the recipient enjoys scent and you want something lighter than Oriental lilies."],
    petSafety: "Generally not listed in the Lilium emergency category; still discourage chewing.",
    pollenNotes: "Usually less messy than lilies; fragrance is the sensitivity issue.",
    facts: ["Freesias were named for German physician Friedrich Freese."],
    relatedFlowers: ["stock", "hyacinth", "rose", "lily"],
    relatedColours: ["white", "yellow", "pink"],
    relatedOccasions: ["wedding", "thank-you"],
    shopQuery: "freesia",
    shopCategory: "flowers",
    faqs: [
      { q: "Are freesias very fragrant?", a: "Many florist cultivars are. If scent is a problem, choose unscented flowers such as gerberas or many modern roses instead." },
      { q: "When are freesias in season?", a: "They are a cool-season crop — strongest in winter and spring in the Northern Hemisphere." },
    ],
    sources: [{ label: "RHS — Freesia" }],
    images: [unsplashImage("photo-1468327768560-75b778cbb551", "White and yellow freesia stems", "freesia-flowers-white-yellow.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Freesia Guide: Fragrance, Season & Care | BlossomPot",
    seoDescription: "Learn why freesias are chosen for scent, when they are in season, and how they compare with lilies for weddings.",
    h1: "Freesia: Fragrance, Season & Care",
  }),
  g({
    slug: "gardenia",
    name: "Gardenia",
    commonNames: ["Cape jasmine"],
    botanicalName: "Gardenia jasminoides",
    family: "Rubiaceae",
    letter: "G",
    shortDescription: "Creamy, highly fragrant blooms used sparingly in luxury work.",
    glance:
      "Gardenias are evergreen shrubs grown for intensely fragrant, creamy flowers. As cut flowers they bruise easily and last a short time, so florists use them sparingly in corsages, hair flowers and luxury posies. They are a plant gift as often as a cut stem. Symbolism often mentions secret love and refinement.",
    whatIs:
      "Gardenia jasminoides, native to Asia, is the common florist and houseplant gardenia.",
    about: [
      "The perfume is the point. The petals brown if touched, chilled wrongly, or left dry — which is why gardenias are a specialist flower, not a grocery bunch.",
      "Potted gardenias need humidity and bright indirect light; they are fussy indoor plants in dry heated homes.",
    ],
    meaning: [
      "Older Western lists link gardenias with secret love, joy and refinement. In the American South they also carry regional garden identity.",
    ],
    colours: [{ colour: "white", label: "Cream-white", association: "Refinement and private affection", occasions: ["wedding", "romantic", "anniversary"] }],
    varieties: [{ name: "Florist gardenia", summary: "Usually double, creamy blooms wired or floated rather than bunched like roses." }],
    season: ["spring", "summer"],
    seasonSummary: "Warm-season shrub bloom; cut use is limited and luxury-priced.",
    seasonDetail: ["Peak outdoor flowering is warm months. Forced plants appear at other times."],
    marketNotes: [
      { market: "us", summary: "Southern garden identity and a corsage classic." },
      { market: "uk", summary: "A luxury, often imported or glasshouse flower." },
      { market: "australia", summary: "Grows well in warmer Australian gardens." },
      { market: "canada", summary: "Mostly a luxury import or indoor plant." },
      { market: "europe", summary: "Glasshouse and imported luxury stem." },
      { market: "uae", summary: "Indoor plant and imported corsage flower; dry air is a challenge." },
    ],
    origin: "East Asia.",
    habitat: "Acid, humus-rich soils in mild, humid climates.",
    appearance: "Waxy, creamy double flowers against glossy leaves.",
    fragrance: "Strong, sweet, jasmine-like.",
    vaseLife: "Short as a cut flower — often only a few days. Handle as little as possible.",
    cutFlower: true,
    bouquetUse: "Accent, corsage, floated bloom — not a bulk bunch.",
    floristUses: "Weddings, anniversary luxury, boutonniere work.",
    care: ["Keep hydrated, cool and untouched. Mist lightly if the florist advises. Do not squeeze petals."],
    occasions: ["wedding", "romantic", "anniversary"],
    occasionNotes: ["Gardenias are a 'small and special' gift, not a long-lasting office bouquet."],
    petSafety: "Gardenia is listed by the ASPCA as non-toxic to dogs and cats; still discourage chewing.",
    pollenNotes: "Fragrance is the main sensitivity.",
    facts: ["The flowers bruise from the oils on skin — even gentle arranging can brown them."],
    relatedFlowers: ["jasmine", "rose", "peony", "tuberose"],
    relatedColours: ["white"],
    relatedOccasions: ["wedding", "romantic"],
    shopQuery: "gardenia",
    shopCategory: "flowers",
    faqs: [
      { q: "Why do gardenias turn brown?", a: "The petals are fragile and bruise from touch, dryness or temperature swings." },
      { q: "Do gardenias last in a vase?", a: "Not as long as roses. They are a short-lived luxury accent." },
    ],
    sources: [{ label: "RHS — Gardenia" }, { label: "ASPCA — Gardenia" }],
    images: [unsplashImage("photo-1499002238440-d264edd596ec", "Cream gardenia bloom", "white-gardenia-flower-close-up.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Gardenia Guide: Fragrance, Meaning & Care | BlossomPot",
    seoDescription: "Learn why gardenias bruise, how they are used in weddings, and what their fragrance-focused gift style means.",
    h1: "Gardenia: Fragrance, Meaning & Care",
  }),
  g({
    slug: "iris",
    name: "Iris",
    commonNames: ["Bearded iris", "Dutch iris", "Flag iris"],
    botanicalName: "Iris",
    family: "Iridaceae",
    letter: "I",
    shortDescription: "Sculptural blooms associated with faith, hope, and wisdom.",
    glance:
      "Iris is a large genus. Florists most often sell Dutch irises (Iris × hollandica) as cut stems in purple, blue, yellow and white. Bearded garden irises are a different, shorter-lived cut. Traditional symbolism includes faith, hope and wisdom. Cut Dutch irises are a cool-season item.",
    whatIs:
      "Iris flowers have three upright standards and three hanging falls. Dutch iris is the main commercial cut.",
    about: [
      "The name comes from the Greek word for rainbow, reflecting the colour range.",
      "Dutch irises are bulb crops forced for late winter and spring shops. Garden bearded irises peak later in spring and do not ship as well.",
    ],
    meaning: [
      "European heraldry and Victorian lists link iris with faith, hope, wisdom and eloquence. The French fleur-de-lis is historically associated with iris (or lily — historians debate the emblem).",
    ],
    colours: [
      { colour: "purple", label: "Purple / blue", association: "Wisdom and royalty in traditional lists", occasions: ["sympathy", "congratulations"] },
      { colour: "yellow", label: "Yellow", association: "Passion or hope depending on the list", occasions: ["get-well"] },
      { colour: "white", label: "White", association: "Purity", occasions: ["sympathy"] },
    ],
    varieties: [
      { name: "Dutch iris", summary: "The slender florist cut stem." },
      { name: "Bearded iris", summary: "Garden plant with fuzzy falls; poor traveller as a cut." },
    ],
    season: ["spring"],
    seasonSummary: "Cool-season cut flower; garden bearded irises follow in late spring.",
    seasonDetail: ["Northern shops see Dutch iris mainly in late winter and spring."],
    marketNotes: [
      { market: "us", summary: "A spring florist stem; bearded irises stay in gardens." },
      { market: "uk", summary: "Dutch iris is a familiar spring bunch." },
      { market: "europe", summary: "Major bulb-forcing crop." },
      { market: "canada", summary: "Imported spring stem." },
      { market: "australia", summary: "Local spring window is reversed." },
      { market: "uae", summary: "Imported in the northern cool season." },
    ],
    origin: "Northern Hemisphere temperate regions; Dutch iris is a hybrid group.",
    habitat: "Gardens and bulb-forcing houses.",
    appearance: "Three standards and three falls; Dutch iris is slimmer than bearded types.",
    fragrance: "Dutch cuts are usually light; some garden irises are fragrant.",
    vaseLife: "Moderate; buds open in the vase over several days.",
    cutFlower: true,
    bouquetUse: "Vertical accent in spring mixed bunches.",
    floristUses: "Sympathy, spring colour, contemporary line arrangements.",
    care: ["Recut, keep cool, and allow pointed buds to open. Avoid heat."],
    occasions: ["sympathy", "congratulations", "get-well"],
    occasionNotes: ["Purple iris can feel respectful without defaulting to funeral white lilies."],
    petSafety: "Iris is listed as toxic if ingested (especially rhizomes). Keep away from pets that chew.",
    pollenNotes: "Generally moderate.",
    facts: ["Iris rhizomes of some species were once a source of orris, used in perfumery."],
    relatedFlowers: ["tulip", "freesia", "lily", "hyacinth"],
    relatedColours: ["purple", "blue", "yellow"],
    relatedOccasions: ["sympathy", "congratulations"],
    shopQuery: "iris",
    shopCategory: "flowers",
    faqs: [
      { q: "What iris do florists sell?", a: "Usually Dutch iris, not the large bearded garden iris." },
      { q: "What does an iris mean?", a: "Traditional Western lists mention faith, hope and wisdom. Treat that as cultural, not required." },
    ],
    sources: [{ label: "RHS — Iris" }, { label: "ASPCA — Iris" }],
    images: [unsplashImage("photo-1468327768560-75b778cbb551", "Purple iris flower", "purple-iris-flower.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Iris Flower Guide: Meaning, Types & Care | BlossomPot",
    seoDescription: "Learn the difference between Dutch and bearded irises, traditional meanings, and spring seasonality.",
    h1: "Iris: Meaning, Types & Care Guide",
  }),
  g({
    slug: "lavender",
    name: "Lavender",
    commonNames: ["English lavender", "Lavandula"],
    botanicalName: "Lavandula",
    family: "Lamiaceae",
    letter: "L",
    shortDescription: "Aromatic herb used in rustic bouquets, favours, and dried work.",
    glance:
      "Lavender is a Mediterranean herb grown for fragrant purple flower spikes. Fresh-cut lavender appears in rustic and wedding work; dried lavender is even more common. It is associated with calm and devotion. It is not a typical long-stem romantic bouquet flower.",
    whatIs:
      "Lavandula species, especially L. angustifolia (English lavender) and lavandin hybrids used for oil and dried bunches.",
    about: [
      "Lavender needs sun and drainage. It is a garden and farm crop more than a tropical greenhouse rose substitute.",
      "Fresh spikes are seasonal in summer in the north. Dried bunches are year-round.",
    ],
    meaning: [
      "Western gifting links lavender with calm, devotion and sometimes distrust in older contradictory lists. Modern use is overwhelmingly 'peace and thoughtfulness'.",
    ],
    colours: [{ colour: "purple", label: "Purple", association: "Calm and devotion", occasions: ["thank-you", "wedding", "just-because"] }],
    varieties: [
      { name: "English lavender", summary: "Sweeter scent; common in gardens and culinary use." },
      { name: "Lavandin", summary: "Larger farm spikes used for oil and dried bunches." },
    ],
    season: ["summer"],
    seasonSummary: "Fresh spikes in summer; dried product all year.",
    seasonDetail: ["Northern harvest is typically midsummer. Australia harvests in the opposite summer."],
    marketNotes: [
      { market: "us", summary: "Farm-stand summer flower and year-round dried gift." },
      { market: "uk", summary: "Classic British summer garden and wedding rustic stem." },
      { market: "europe", summary: "Provence and other Mediterranean regions are cultural reference points." },
      { market: "canada", summary: "Short summer harvest; dried product year-round." },
      { market: "australia", summary: "Local summer harvest in cooler regions." },
      { market: "uae", summary: "Mostly dried or imported; heat and humidity challenge fresh spikes." },
    ],
    origin: "Mediterranean basin.",
    habitat: "Dry, sunny slopes and gardens.",
    appearance: "Slender spikes of small tubular flowers on square mint-family stems.",
    fragrance: "Strong, herbal-sweet.",
    vaseLife: "Fresh spikes are moderate; dried last months.",
    cutFlower: true,
    bouquetUse: "Rustic mixed bunches, favours, dried bundles.",
    floristUses: "Wedding rustic, thank-you, aromatherapy-adjacent gifts.",
    care: ["Use little water for fresh stems; hang to dry in a dark, airy place if preserving."],
    occasions: ["thank-you", "wedding", "just-because"],
    occasionNotes: ["Lavender suits a calm thank-you more than a formal anniversary dozen."],
    petSafety: "Lavender oil can be problematic; the plant is not in the lily emergency class. Keep concentrated oils away from pets.",
    pollenNotes: "Generally considered lower-pollen than wind-pollinated plants; fragrance is the issue for sensitive people.",
    facts: ["Lavender is a mint-family herb, not a lily or rose relative."],
    relatedFlowers: ["stock", "freesia", "rose", "statice"],
    relatedColours: ["purple", "blue"],
    relatedOccasions: ["thank-you", "wedding"],
    shopQuery: "lavender",
    shopCategory: "flowers",
    faqs: [
      { q: "Is lavender a cut flower?", a: "Yes, but it is used as a scented accent or dried bundle more than as a large formal bouquet." },
      { q: "When is lavender in season?", a: "Fresh spikes are a summer harvest in the Northern Hemisphere. Dried lavender is sold all year." },
    ],
    sources: [{ label: "RHS — Lavandula" }],
    images: [unsplashImage("photo-1499002238440-d264edd596ec", "Purple lavender field stems", "purple-lavender-flowers.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Lavender Guide: Meaning, Season & Uses | BlossomPot",
    seoDescription: "Learn how fresh and dried lavender differ, when spikes are in season, and why lavender suits rustic gifts.",
    h1: "Lavender: Meaning, Season & Care",
  }),
  g({
    slug: "lisianthus",
    name: "Lisianthus",
    commonNames: ["Prairie gentian", "Eustoma"],
    botanicalName: "Eustoma grandiflorum",
    family: "Gentianaceae",
    letter: "L",
    shortDescription: "Rose-like florist flower with a long vase life.",
    glance:
      "Lisianthus (Eustoma) is a prairie gentian grown as a cut flower that resembles a softer rose or ranunculus. It lasts well and is popular in weddings. It is available much of the year from specialist growers, with a natural summer association.",
    whatIs:
      "Eustoma grandiflorum, native to North America, bred into single and double cut-flower forms.",
    about: [
      "Lisianthus became a late-twentieth-century florist favourite because it looks luxurious and ships better than garden roses of similar softness.",
      "Colours include white, blush, pink, purple and picotee edges.",
    ],
    meaning: [
      "Modern lists assign appreciation, charisma and a outgoing nature. There is less old European floriography than for roses.",
    ],
    colours: [
      { colour: "white", label: "White", association: "Grace", occasions: ["wedding"] },
      { colour: "pink", label: "Pink", association: "Appreciation", occasions: ["thank-you", "anniversary"] },
      { colour: "purple", label: "Purple", association: "Admiration", occasions: ["congratulations"] },
      { colour: "peach", label: "Blush / peach", association: "Soft romance", occasions: ["wedding", "romantic"] },
    ],
    varieties: [
      { name: "Double lisianthus", summary: "The rose-like florist form." },
      { name: "Single lisianthus", summary: "More poppy-like, lighter look." },
    ],
    season: ["summer", "year-round"],
    seasonSummary: "Summer garden association; commercial cuts much of the year.",
    seasonDetail: ["Quality is often best in the natural warm-season flush."],
    marketNotes: sharedMarketsYearRound,
    origin: "North American grasslands.",
    habitat: "Sunny, well-drained sites; greenhouse cuts commercially.",
    appearance: "Satiny petals, often ruffled, on branching stems.",
    fragrance: "Light.",
    vaseLife: "Often long — a week or more as buds continue to open.",
    cutFlower: true,
    bouquetUse: "Wedding and luxury mixed designs as a rose alternative.",
    floristUses: "Bridal, anniversary, thank-you.",
    care: ["Recut, remove lower leaves, and give buds time to open. Avoid ethylene (fruit bowls)."],
    occasions: ["wedding", "anniversary", "thank-you"],
    occasionNotes: ["Choose lisianthus when you want a rose look with a slightly softer, less clichéd reading."],
    petSafety: "Not typically listed as a severe toxin; still discourage ingestion.",
    pollenNotes: "Usually modest.",
    facts: ["It is a gentian relative, not a rose, despite the nickname 'rose-like'."],
    relatedFlowers: ["rose", "ranunculus", "peony", "alstroemeria"],
    relatedColours: ["white", "pink", "purple"],
    relatedOccasions: ["wedding", "anniversary"],
    shopQuery: "lisianthus",
    shopCategory: "flowers",
    faqs: [
      { q: "Is lisianthus a type of rose?", a: "No. It only looks similar. It is Eustoma, a gentian-family flower." },
      { q: "Does lisianthus last well?", a: "Yes. It is valued for a relatively long vase life as buds open." },
    ],
    sources: [{ label: "RHS — Eustoma" }],
    images: [unsplashImage("photo-1561181286-d3fee7d55364", "Pink lisianthus blooms", "pink-lisianthus-flowers.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Lisianthus Guide: Rose-Like Flower Meaning & Care | BlossomPot",
    seoDescription: "Learn why lisianthus is used as a rose alternative in weddings, plus colours, vase life and care.",
    h1: "Lisianthus: Meaning, Colours & Care",
  }),
  g({
    slug: "ranunculus",
    name: "Ranunculus",
    commonNames: ["Persian buttercup"],
    botanicalName: "Ranunculus asiaticus",
    family: "Ranunculaceae",
    letter: "R",
    shortDescription: "Layered spring bloom often compared with peonies and roses.",
    glance:
      "Ranunculus (Persian buttercup) is a cool-season tuber crop with densely layered petals. Florists use it as a peony or garden-rose lookalike in late winter and spring. The natural season is short; some imports extend it. The plants are toxic if eaten.",
    whatIs:
      "Ranunculus asiaticus, native to the eastern Mediterranean, grown from tuberous roots for cut flowers.",
    about: [
      "The charm is the paper-like swirl of petals in almost every colour except true blue.",
      "Stems are hollow and delicate. They suit wedding work and compact posies more than rough shipping as a grocery add-on.",
    ],
    meaning: [
      "Modern lists mention radiant charm and attractiveness. There is less fixed Victorian coding than for roses.",
    ],
    colours: [
      { colour: "pink", label: "Pink", association: "Romance", occasions: ["wedding", "romantic"] },
      { colour: "peach", label: "Peach", association: "Warm modern weddings", occasions: ["wedding", "anniversary"] },
      { colour: "white", label: "White", association: "Elegance", occasions: ["wedding"] },
      { colour: "red", label: "Red", association: "Richer affection", occasions: ["romantic"] },
      { colour: "yellow", label: "Yellow", association: "Cheer", occasions: ["birthday"] },
    ],
    varieties: [{ name: "Clooney and similar florist series", summary: "Large, densely petalled commercial types." }],
    season: ["spring", "winter"],
    seasonSummary: "Cool-season flower; peak late winter and spring in the north.",
    seasonDetail: ["Heat ends quality quickly. Opposite-hemisphere farms supply some off-season weddings."],
    marketNotes: [
      { market: "us", summary: "A late-winter and spring wedding favourite." },
      { market: "uk", summary: "Peak in the British spring wedding calendar." },
      { market: "europe", summary: "Mediterranean and Dutch production for the cool season." },
      { market: "canada", summary: "Imported cool-season wedding flower." },
      { market: "australia", summary: "Local cool-season window." },
      { market: "uae", summary: "Imported luxury stem for cool indoor settings." },
    ],
    origin: "Eastern Mediterranean.",
    habitat: "Cool growing conditions; greenhouse and field production.",
    appearance: "Many tissue-thin petals in a tight swirl; hollow stems.",
    fragrance: "Light.",
    vaseLife: "Often around a week if kept cool; heat collapses them.",
    cutFlower: true,
    bouquetUse: "Wedding and compact romantic posies.",
    floristUses: "Bridal, anniversary, spring luxury mixed.",
    care: ["Recut hollow stems carefully, keep cool, and do not overcrowd. Change water often."],
    occasions: ["wedding", "anniversary", "romantic", "birthday"],
    occasionNotes: ["A spring alternative when peonies are not yet local."],
    petSafety: "Ranunculus contains irritating compounds and is considered toxic if ingested. Keep away from pets and children who might chew stems.",
    pollenNotes: "Doubles are relatively tidy.",
    facts: ["The name means 'little frog', a reference to the wet habitats of some wild buttercups — not to the florist crop's look."],
    relatedFlowers: ["peony", "rose", "tulip", "lisianthus"],
    relatedColours: ["pink", "peach", "white"],
    relatedOccasions: ["wedding", "romantic", "anniversary"],
    shopQuery: "ranunculus",
    shopCategory: "flowers",
    faqs: [
      { q: "Are ranunculus like peonies?", a: "They can look similar when fully open, but they are a different plant with a cooler, earlier season." },
      { q: "When are ranunculus in season?", a: "Late winter and spring in the Northern Hemisphere, with some imported supply outside that window." },
    ],
    sources: [{ label: "RHS — Ranunculus" }, { label: "ASPCA — Buttercup (related genus toxicity context)" }],
    images: [unsplashImage("photo-1561181286-d3fee7d55364", "Peach ranunculus with many petals", "peach-ranunculus-flower.jpg", "Annie Spratt", "hero")],
    status: "published",
    publishedAt: "2026-08-16",
    updatedAt: UPDATED,
    reviewedBy: TEAM,
    seoTitle: "Ranunculus Guide: Season, Meaning & Care | BlossomPot",
    seoDescription: "Compare ranunculus with peonies and roses, and learn the cool-season window that makes them a spring wedding flower.",
    h1: "Ranunculus: Season, Meaning & Care",
  }),
];
