import { unsplashImage } from "./images";
import type { FlowerDirectoryEntry } from "./types";

/**
 * Core flower directory. Published guides are expanded in `published/`.
 * Remaining entries stay researching until a reviewed guide exists.
 */
export const flowerDirectory: FlowerDirectoryEntry[] = [
  {
    slug: "alstroemeria",
    name: "Alstroemeria",
    letter: "A",
    shortDescription: "Long-lasting Peruvian lily used in mixed bouquets.",
    colours: ["pink", "orange", "yellow", "white", "purple", "mixed"],
    season: ["spring", "summer", "year-round"],
    meaning: "Friendship and devotion",
    occasions: ["birthday", "thank-you", "congratulations", "just-because"],
    fragrance: "light",
    longevity: "long",
    petFriendly: false,
    categories: ["popular", "long-lasting"],
    status: "published",
    image: unsplashImage("photo-1468327768560-75b778cbb551", "Pink alstroemeria blooms", "alstroemeria-pink-flowers.jpg", "Annie Spratt"),
  },
  {
    slug: "amaryllis",
    name: "Amaryllis",
    letter: "A",
    shortDescription: "Large winter-flowering bulbs often given as festive plants.",
    colours: ["red", "white", "pink", "peach"],
    season: ["winter"],
    meaning: "Pride and determination",
    occasions: ["housewarming", "congratulations", "just-because"],
    fragrance: "light",
    longevity: "medium",
    categories: ["winter", "luxury"],
    status: "researching",
  },
  {
    slug: "anemone",
    name: "Anemone",
    letter: "A",
    shortDescription: "Papery spring blooms with a dark centre, popular in weddings.",
    colours: ["white", "pink", "red", "purple", "blue"],
    season: ["spring", "winter"],
    meaning: "Anticipation",
    occasions: ["wedding", "romantic", "sympathy"],
    fragrance: "none",
    longevity: "short",
    categories: ["wedding", "spring", "romantic"],
    status: "researching",
  },
  {
    slug: "anthurium",
    name: "Anthurium",
    letter: "A",
    shortDescription: "Glossy tropical spathes used as cut flowers and houseplants.",
    colours: ["red", "pink", "white", "green"],
    season: ["year-round"],
    meaning: "Hospitality",
    occasions: ["housewarming", "congratulations", "corporate"],
    fragrance: "none",
    longevity: "long",
    categories: ["exotic", "long-lasting", "indoor"],
    status: "researching",
  },
  {
    slug: "aster",
    name: "Aster",
    letter: "A",
    shortDescription: "Daisy-like late-season flowers associated with patience.",
    colours: ["purple", "pink", "white", "blue"],
    season: ["autumn"],
    meaning: "Patience and elegance",
    occasions: ["birthday", "thank-you", "just-because"],
    fragrance: "light",
    longevity: "medium",
    categories: ["autumn", "wildflowers"],
    status: "researching",
  },
  {
    slug: "azalea",
    name: "Azalea",
    letter: "A",
    shortDescription: "Spring-flowering shrubs more often gifted as plants than cuts.",
    colours: ["pink", "red", "white", "peach"],
    season: ["spring"],
    meaning: "Temperance and home",
    occasions: ["housewarming", "mothers-day"],
    fragrance: "light",
    longevity: "medium",
    petFriendly: false,
    categories: ["spring", "indoor"],
    status: "researching",
  },
  {
    slug: "babys-breath",
    name: "Baby's Breath",
    letter: "B",
    shortDescription: "Airy filler flower used in bouquets and wedding work.",
    colours: ["white", "pink"],
    season: ["year-round"],
    meaning: "Everlasting love and innocence",
    occasions: ["wedding", "new-baby", "romantic", "sympathy"],
    fragrance: "light",
    longevity: "long",
    categories: ["wedding", "popular", "long-lasting"],
    status: "published",
    image: unsplashImage("photo-1468327768560-75b778cbb551", "White baby's breath in a loose bouquet", "babys-breath-white-bouquet.jpg", "Annie Spratt"),
  },
  {
    slug: "begonia",
    name: "Begonia",
    letter: "B",
    shortDescription: "Shade-loving garden and indoor plants with colourful blooms.",
    colours: ["pink", "red", "white", "orange"],
    season: ["summer"],
    meaning: "Caution and uniqueness",
    occasions: ["housewarming", "just-because"],
    fragrance: "none",
    longevity: "medium",
    categories: ["indoor"],
    status: "researching",
  },
  {
    slug: "bird-of-paradise",
    name: "Bird of Paradise",
    letter: "B",
    shortDescription: "Architectural tropical flower used in modern arrangements.",
    colours: ["orange", "blue"],
    season: ["year-round"],
    meaning: "Joy and magnificence",
    occasions: ["congratulations", "corporate", "housewarming"],
    fragrance: "none",
    longevity: "medium",
    categories: ["exotic", "luxury"],
    status: "researching",
  },
  {
    slug: "bluebell",
    name: "Bluebell",
    letter: "B",
    shortDescription: "Woodland spring flower, especially associated with British woods.",
    colours: ["blue", "purple"],
    season: ["spring"],
    meaning: "Humility and gratitude",
    occasions: ["thank-you", "just-because"],
    fragrance: "moderate",
    longevity: "short",
    categories: ["spring", "wildflowers", "fragrant"],
    status: "researching",
  },
  {
    slug: "bougainvillea",
    name: "Bougainvillea",
    letter: "B",
    shortDescription: "Warm-climate vine grown for colourful bracts rather than cut work.",
    colours: ["pink", "purple", "orange", "white"],
    season: ["summer"],
    meaning: "Passion",
    occasions: ["housewarming"],
    fragrance: "none",
    longevity: "short",
    categories: ["exotic"],
    status: "researching",
  },
  {
    slug: "calla-lily",
    name: "Calla Lily",
    letter: "C",
    shortDescription: "Sculptural spathe flower used in weddings and formal designs.",
    colours: ["white", "pink", "yellow", "orange", "purple"],
    season: ["spring", "summer", "year-round"],
    meaning: "Elegance and rebirth",
    occasions: ["wedding", "sympathy", "congratulations"],
    fragrance: "light",
    longevity: "medium",
    petFriendly: false,
    categories: ["wedding", "luxury", "popular"],
    status: "published",
    image: unsplashImage("photo-1455659817273-f093b0cdc19e", "White calla lily spathes", "white-calla-lily-flowers.jpg", "Annie Spratt"),
  },
  {
    slug: "carnation",
    name: "Carnation",
    letter: "C",
    shortDescription: "Ruffled, long-lasting florist staple with colour-specific meanings.",
    colours: ["red", "pink", "white", "yellow", "purple", "peach"],
    season: ["year-round"],
    meaning: "Love, distinction, and remembrance",
    occasions: ["mothers-day", "birthday", "sympathy", "thank-you"],
    fragrance: "moderate",
    longevity: "long",
    categories: ["popular", "long-lasting", "fragrant"],
    status: "published",
    image: unsplashImage("photo-1468327768560-75b778cbb551", "Pink carnation petals", "pink-carnation-flower.jpg", "Annie Spratt"),
  },
  {
    slug: "chrysanthemum",
    name: "Chrysanthemum",
    letter: "C",
    shortDescription: "Autumn florist favourite with many forms and cultural meanings.",
    colours: ["yellow", "white", "pink", "red", "orange", "purple"],
    season: ["autumn", "year-round"],
    meaning: "Joy, longevity, and in some cultures grief",
    occasions: ["birthday", "sympathy", "congratulations", "just-because"],
    fragrance: "light",
    longevity: "long",
    petFriendly: false,
    categories: ["autumn", "popular", "long-lasting"],
    status: "published",
    image: unsplashImage("photo-1508610048659-a06b669e3321", "Yellow chrysanthemum bloom", "yellow-chrysanthemum-flower.jpg", "Annie Spratt"),
  },
  {
    slug: "clematis",
    name: "Clematis",
    letter: "C",
    shortDescription: "Climbing garden vine rarely used as a standard cut flower.",
    colours: ["purple", "pink", "white", "blue"],
    season: ["summer"],
    meaning: "Mental beauty",
    occasions: ["just-because"],
    fragrance: "light",
    longevity: "short",
    petFriendly: false,
    categories: ["wildflowers"],
    status: "researching",
  },
  {
    slug: "cosmos",
    name: "Cosmos",
    letter: "C",
    shortDescription: "Open, airy garden flowers with a meadow character.",
    colours: ["pink", "white", "orange"],
    season: ["summer", "autumn"],
    meaning: "Order and peace",
    occasions: ["just-because", "thank-you"],
    fragrance: "none",
    longevity: "short",
    categories: ["summer", "wildflowers"],
    status: "researching",
  },
  {
    slug: "crocus",
    name: "Crocus",
    letter: "C",
    shortDescription: "Early spring bulb, more garden than florist cut flower.",
    colours: ["purple", "yellow", "white"],
    season: ["spring", "winter"],
    meaning: "Youthful gladness",
    occasions: ["just-because"],
    fragrance: "light",
    longevity: "short",
    categories: ["spring"],
    status: "researching",
  },
  {
    slug: "dahlia",
    name: "Dahlia",
    letter: "D",
    shortDescription: "Late-summer show flower prized for form and colour range.",
    colours: ["pink", "red", "orange", "yellow", "white", "purple", "peach"],
    season: ["summer", "autumn"],
    meaning: "Dignity and inner strength",
    occasions: ["wedding", "birthday", "congratulations"],
    fragrance: "none",
    longevity: "medium",
    categories: ["summer", "autumn", "luxury"],
    status: "published",
    image: unsplashImage("photo-1561181286-d3fee7d55364", "Pink dahlia with layered petals", "pink-dahlia-flower-close-up.jpg", "Annie Spratt"),
  },
  {
    slug: "daffodil",
    name: "Daffodil",
    letter: "D",
    shortDescription: "Iconic spring trumpet flower; keep away from other cuts when first opening.",
    colours: ["yellow", "white", "orange"],
    season: ["spring"],
    meaning: "New beginnings",
    occasions: ["birthday", "congratulations", "get-well"],
    fragrance: "light",
    longevity: "medium",
    petFriendly: false,
    categories: ["spring"],
    status: "researching",
  },
  {
    slug: "delphinium",
    name: "Delphinium",
    letter: "D",
    shortDescription: "Tall blue flower spikes used in garden-style arrangements.",
    colours: ["blue", "purple", "white", "pink"],
    season: ["summer"],
    meaning: "Openness and big-heartedness",
    occasions: ["wedding", "congratulations"],
    fragrance: "light",
    longevity: "medium",
    petFriendly: false,
    categories: ["summer", "wedding"],
    status: "researching",
  },
  {
    slug: "dianthus",
    name: "Dianthus",
    letter: "D",
    shortDescription: "Family that includes carnations, pinks, and sweet William.",
    colours: ["pink", "red", "white"],
    season: ["spring", "summer", "year-round"],
    meaning: "Affection",
    occasions: ["birthday", "thank-you", "mothers-day"],
    fragrance: "moderate",
    longevity: "long",
    categories: ["popular", "fragrant", "long-lasting"],
    status: "researching",
  },
  {
    slug: "echinacea",
    name: "Echinacea",
    letter: "E",
    shortDescription: "Coneflower used more in gardens and herbal contexts than bouquets.",
    colours: ["pink", "purple", "orange", "white"],
    season: ["summer"],
    meaning: "Strength and healing",
    occasions: ["get-well", "just-because"],
    fragrance: "none",
    longevity: "medium",
    categories: ["summer", "wildflowers"],
    status: "researching",
  },
  {
    slug: "edelweiss",
    name: "Edelweiss",
    letter: "E",
    shortDescription: "Alpine symbol of devotion; rarely a commercial cut flower.",
    colours: ["white"],
    season: ["summer"],
    meaning: "Courage and devotion",
    occasions: ["romantic"],
    fragrance: "none",
    longevity: "medium",
    categories: ["wildflowers"],
    status: "researching",
  },
  {
    slug: "english-rose",
    name: "English Rose",
    letter: "E",
    shortDescription: "Garden-style rose group known for cupped form and fragrance.",
    colours: ["pink", "peach", "yellow", "white", "red"],
    season: ["spring", "summer"],
    meaning: "Romance and English garden charm",
    occasions: ["wedding", "anniversary", "romantic"],
    fragrance: "strong",
    longevity: "medium",
    categories: ["romantic", "wedding", "luxury", "fragrant"],
    status: "researching",
  },
  {
    slug: "freesia",
    name: "Freesia",
    letter: "F",
    shortDescription: "Fragrant, funnel-shaped stems used in spring and wedding work.",
    colours: ["white", "yellow", "pink", "purple", "orange"],
    season: ["spring", "winter"],
    meaning: "Trust and thoughtfulness",
    occasions: ["wedding", "thank-you", "anniversary"],
    fragrance: "strong",
    longevity: "medium",
    categories: ["fragrant", "wedding", "spring"],
    status: "published",
    image: unsplashImage("photo-1468327768560-75b778cbb551", "White and yellow freesia stems", "freesia-flowers-white-yellow.jpg", "Annie Spratt"),
  },
  {
    slug: "foxglove",
    name: "Foxglove",
    letter: "F",
    shortDescription: "Tall garden spires; toxic and not a typical commercial cut flower.",
    colours: ["pink", "purple", "white"],
    season: ["summer"],
    meaning: "Insincerity in older floriography",
    occasions: ["just-because"],
    fragrance: "none",
    longevity: "short",
    petFriendly: false,
    categories: ["summer"],
    status: "researching",
  },
  {
    slug: "gardenia",
    name: "Gardenia",
    letter: "G",
    shortDescription: "Creamy, highly fragrant blooms used sparingly in luxury work.",
    colours: ["white"],
    season: ["spring", "summer"],
    meaning: "Secret love and refinement",
    occasions: ["wedding", "romantic", "anniversary"],
    fragrance: "strong",
    longevity: "short",
    petFriendly: false,
    categories: ["fragrant", "luxury", "wedding"],
    status: "published",
    image: unsplashImage("photo-1499002238440-d264edd596ec", "Cream gardenia bloom", "white-gardenia-flower-close-up.jpg", "Annie Spratt"),
  },
  {
    slug: "gerbera",
    name: "Gerbera",
    letter: "G",
    shortDescription: "Cheerful daisy-form cut flower in a wide colour range.",
    colours: ["pink", "red", "orange", "yellow", "white"],
    season: ["year-round"],
    meaning: "Cheerfulness",
    occasions: ["birthday", "get-well", "congratulations", "just-because"],
    fragrance: "none",
    longevity: "medium",
    categories: ["popular", "birthday"],
    status: "published",
    image: unsplashImage("photo-1508610048659-a06b669e3321", "Orange gerbera daisy", "orange-gerbera-daisy-flower.jpg", "Annie Spratt"),
  },
  {
    slug: "gladiolus",
    name: "Gladiolus",
    letter: "G",
    shortDescription: "Tall summer spike used in sympathy and ceremonial designs.",
    colours: ["pink", "red", "yellow", "white", "purple", "orange"],
    season: ["summer"],
    meaning: "Strength of character",
    occasions: ["sympathy", "congratulations", "funeral"],
    fragrance: "none",
    longevity: "medium",
    categories: ["summer"],
    status: "researching",
  },
  {
    slug: "gomphrena",
    name: "Gomphrena",
    letter: "G",
    shortDescription: "Globe amaranth used as a long-lasting dried or fresh filler.",
    colours: ["pink", "purple", "orange", "white"],
    season: ["summer"],
    meaning: "Unfading love",
    occasions: ["just-because"],
    fragrance: "none",
    longevity: "long",
    categories: ["summer", "long-lasting"],
    status: "researching",
  },
  {
    slug: "heather",
    name: "Heather",
    letter: "H",
    shortDescription: "Small-flowered shrub associated with Scotland and good luck.",
    colours: ["purple", "pink", "white"],
    season: ["summer", "autumn"],
    meaning: "Good luck and admiration",
    occasions: ["congratulations", "just-because"],
    fragrance: "light",
    longevity: "medium",
    categories: ["wildflowers"],
    status: "researching",
  },
  {
    slug: "hibiscus",
    name: "Hibiscus",
    letter: "H",
    shortDescription: "Tropical bloom more common as a plant than a cut flower.",
    colours: ["red", "pink", "orange", "yellow", "white"],
    season: ["summer"],
    meaning: "Delicate beauty",
    occasions: ["just-because", "housewarming"],
    fragrance: "none",
    longevity: "short",
    categories: ["exotic", "summer"],
    status: "researching",
  },
  {
    slug: "honeysuckle",
    name: "Honeysuckle",
    letter: "H",
    shortDescription: "Fragrant climbing vine, uncommon as a commercial cut stem.",
    colours: ["yellow", "white", "pink"],
    season: ["summer"],
    meaning: "Bonds of love",
    occasions: ["romantic"],
    fragrance: "strong",
    longevity: "short",
    categories: ["fragrant", "wildflowers"],
    status: "researching",
  },
  {
    slug: "hydrangea",
    name: "Hydrangea",
    letter: "H",
    shortDescription: "Large clustered heads used in weddings and statement bouquets.",
    colours: ["blue", "pink", "white", "purple", "green"],
    season: ["spring", "summer", "autumn"],
    meaning: "Gratitude and understanding",
    occasions: ["wedding", "thank-you", "mothers-day", "housewarming"],
    fragrance: "none",
    longevity: "medium",
    petFriendly: false,
    categories: ["wedding", "popular", "luxury"],
    status: "published",
    image: unsplashImage("photo-1599733594230-6b5631bdc1e0", "Blue hydrangea flower head", "blue-hydrangea-flower-close-up.jpg", "Annie Spratt"),
  },
  {
    slug: "hyacinth",
    name: "Hyacinth",
    letter: "H",
    shortDescription: "Intensely fragrant spring spike, also sold as a potted bulb.",
    colours: ["purple", "pink", "white", "blue"],
    season: ["spring", "winter"],
    meaning: "Playfulness and constancy",
    occasions: ["birthday", "thank-you"],
    fragrance: "strong",
    longevity: "medium",
    petFriendly: false,
    categories: ["spring", "fragrant"],
    status: "researching",
  },
  {
    slug: "iris",
    name: "Iris",
    letter: "I",
    shortDescription: "Sculptural blooms associated with faith, hope, and wisdom.",
    colours: ["purple", "blue", "yellow", "white"],
    season: ["spring"],
    meaning: "Faith, hope, and wisdom",
    occasions: ["sympathy", "congratulations", "get-well"],
    fragrance: "light",
    longevity: "medium",
    petFriendly: false,
    categories: ["spring"],
    status: "published",
    image: unsplashImage("photo-1468327768560-75b778cbb551", "Purple iris flower", "purple-iris-flower.jpg", "Annie Spratt"),
  },
  {
    slug: "ixora",
    name: "Ixora",
    letter: "I",
    shortDescription: "Tropical cluster flower grown as a landscape and pot plant.",
    colours: ["red", "orange", "pink", "yellow"],
    season: ["summer"],
    meaning: "Passion",
    occasions: ["just-because"],
    fragrance: "none",
    longevity: "short",
    categories: ["exotic"],
    status: "researching",
  },
  {
    slug: "jasmine",
    name: "Jasmine",
    letter: "J",
    shortDescription: "Night-scented vine used more in fragrance and décor than large bouquets.",
    colours: ["white", "yellow"],
    season: ["summer"],
    meaning: "Amiability and attachment",
    occasions: ["wedding", "romantic"],
    fragrance: "strong",
    longevity: "short",
    categories: ["fragrant", "wedding"],
    status: "researching",
  },
  {
    slug: "jonquil",
    name: "Jonquil",
    letter: "J",
    shortDescription: "Fragrant daffodil group (Narcissus jonquilla) for late winter and spring.",
    colours: ["yellow", "white"],
    season: ["spring"],
    meaning: "Desire and returned affection",
    occasions: ["romantic", "just-because"],
    fragrance: "strong",
    longevity: "medium",
    petFriendly: false,
    categories: ["spring", "fragrant"],
    status: "researching",
  },
  {
    slug: "kalanchoe",
    name: "Kalanchoe",
    letter: "K",
    shortDescription: "Succulent flowering houseplant rather than a cut-flower crop.",
    colours: ["red", "pink", "orange", "yellow", "white"],
    season: ["winter", "spring"],
    meaning: "enduring affection",
    occasions: ["housewarming", "just-because"],
    fragrance: "none",
    longevity: "long",
    petFriendly: false,
    categories: ["indoor", "long-lasting"],
    status: "researching",
  },
  {
    slug: "lavender",
    name: "Lavender",
    letter: "L",
    shortDescription: "Aromatic herb used in rustic bouquets, favours, and dried work.",
    colours: ["purple", "blue"],
    season: ["summer"],
    meaning: "Calm and devotion",
    occasions: ["thank-you", "wedding", "just-because"],
    fragrance: "strong",
    longevity: "long",
    categories: ["fragrant", "summer", "low-pollen"],
    status: "published",
    image: unsplashImage("photo-1499002238440-d264edd596ec", "Purple lavender field stems", "purple-lavender-flowers.jpg", "Annie Spratt"),
  },
  {
    slug: "lilac",
    name: "Lilac",
    letter: "L",
    shortDescription: "Short-season fragrant shrub bloom associated with spring.",
    colours: ["purple", "pink", "white"],
    season: ["spring"],
    meaning: "First love and youthful innocence",
    occasions: ["romantic", "mothers-day", "wedding"],
    fragrance: "strong",
    longevity: "short",
    categories: ["spring", "fragrant"],
    status: "researching",
  },
  {
    slug: "lily",
    name: "Lily",
    letter: "L",
    shortDescription: "True lilies (Lilium) used in sympathy, Easter, and celebration work.",
    colours: ["white", "pink", "orange", "yellow", "red"],
    season: ["spring", "summer", "year-round"],
    meaning: "Purity, renewal, and remembrance",
    occasions: ["sympathy", "wedding", "congratulations", "funeral"],
    fragrance: "strong",
    longevity: "long",
    petFriendly: false,
    categories: ["popular", "fragrant"],
    status: "published",
    image: unsplashImage("photo-1508610048659-a06b669e3321", "White lily with visible stamens", "white-lily-flower-close-up.jpg", "Annie Spratt"),
  },
  {
    slug: "lily-of-the-valley",
    name: "Lily of the Valley",
    letter: "L",
    shortDescription: "Tiny fragrant bells associated with May and royal bouquets.",
    colours: ["white"],
    season: ["spring"],
    meaning: "Return of happiness",
    occasions: ["wedding", "mothers-day"],
    fragrance: "strong",
    longevity: "short",
    petFriendly: false,
    categories: ["spring", "wedding", "fragrant", "luxury"],
    status: "researching",
  },
  {
    slug: "lisianthus",
    name: "Lisianthus",
    letter: "L",
    shortDescription: "Rose-like florist flower with a long vase life.",
    colours: ["white", "pink", "purple", "peach"],
    season: ["summer", "year-round"],
    meaning: "Appreciation and charisma",
    occasions: ["wedding", "anniversary", "thank-you"],
    fragrance: "light",
    longevity: "long",
    categories: ["wedding", "luxury", "long-lasting"],
    status: "published",
    image: unsplashImage("photo-1561181286-d3fee7d55364", "Pink lisianthus blooms", "pink-lisianthus-flowers.jpg", "Annie Spratt"),
  },
  {
    slug: "lotus",
    name: "Lotus",
    letter: "L",
    shortDescription: "Aquatic flower with deep cultural symbolism; limited cut use.",
    colours: ["pink", "white"],
    season: ["summer"],
    meaning: "Purity and spiritual awakening",
    occasions: ["sympathy", "congratulations"],
    fragrance: "light",
    longevity: "short",
    categories: ["exotic"],
    status: "researching",
  },
  {
    slug: "magnolia",
    name: "Magnolia",
    letter: "M",
    shortDescription: "Large, often fragrant tree blooms; short commercial cut window.",
    colours: ["white", "pink", "peach"],
    season: ["spring"],
    meaning: "Dignity and perseverance",
    occasions: ["wedding", "congratulations"],
    fragrance: "moderate",
    longevity: "short",
    categories: ["spring", "luxury"],
    status: "researching",
  },
  {
    slug: "marigold",
    name: "Marigold",
    letter: "M",
    shortDescription: "Bright garden annual with strong cultural uses, including remembrance.",
    colours: ["orange", "yellow"],
    season: ["summer", "autumn"],
    meaning: "Passion and remembrance",
    occasions: ["just-because"],
    fragrance: "moderate",
    longevity: "medium",
    categories: ["summer", "autumn"],
    status: "researching",
  },
  {
    slug: "mimosa",
    name: "Mimosa",
    letter: "M",
    shortDescription: "Fluffy yellow spring blossom associated with Women's Day in parts of Europe.",
    colours: ["yellow"],
    season: ["spring", "winter"],
    meaning: "Sensitivity and celebration",
    occasions: ["congratulations", "mothers-day"],
    fragrance: "moderate",
    longevity: "short",
    categories: ["spring"],
    status: "researching",
  },
  {
    slug: "morning-glory",
    name: "Morning Glory",
    letter: "M",
    shortDescription: "Garden vine that opens in the morning; not a standard cut flower.",
    colours: ["blue", "purple", "pink", "white"],
    season: ["summer"],
    meaning: "Affection and mortality in older symbolism",
    occasions: ["just-because"],
    fragrance: "none",
    longevity: "short",
    petFriendly: false,
    categories: ["summer"],
    status: "researching",
  },
  {
    slug: "narcissus",
    name: "Narcissus",
    letter: "N",
    shortDescription: "Genus that includes daffodils and paperwhites.",
    colours: ["yellow", "white"],
    season: ["spring", "winter"],
    meaning: "Rebirth and self-reflection",
    occasions: ["congratulations", "just-because"],
    fragrance: "moderate",
    longevity: "medium",
    petFriendly: false,
    categories: ["spring", "winter"],
    status: "researching",
  },
  {
    slug: "nasturtium",
    name: "Nasturtium",
    letter: "N",
    shortDescription: "Edible garden flower with a peppery scent; uncommon in florist work.",
    colours: ["orange", "yellow", "red"],
    season: ["summer"],
    meaning: "Patriotism and conquest in older lists",
    occasions: ["just-because"],
    fragrance: "light",
    longevity: "short",
    categories: ["summer"],
    status: "researching",
  },
  {
    slug: "nerine",
    name: "Nerine",
    letter: "N",
    shortDescription: "Autumn bulb with wavy petals, used in specialist florist work.",
    colours: ["pink", "white"],
    season: ["autumn"],
    meaning: "Freedom",
    occasions: ["just-because"],
    fragrance: "light",
    longevity: "medium",
    categories: ["autumn"],
    status: "researching",
  },
  {
    slug: "orchid",
    name: "Orchid",
    letter: "O",
    shortDescription: "Diverse family; moth orchids are the most common gift plants.",
    colours: ["white", "pink", "purple", "yellow", "green"],
    season: ["year-round"],
    meaning: "Refinement and strength",
    occasions: ["anniversary", "congratulations", "housewarming", "corporate"],
    fragrance: "light",
    longevity: "long",
    petFriendly: true,
    categories: ["luxury", "exotic", "indoor", "long-lasting", "popular"],
    status: "published",
    image: unsplashImage("photo-1566938064504-a380d867ac89", "White moth orchid blooms", "white-orchid-flower-close-up.jpg", "Annie Spratt"),
  },
  {
    slug: "osteospermum",
    name: "Osteospermum",
    letter: "O",
    shortDescription: "African daisy used mainly as a garden and patio plant.",
    colours: ["purple", "white", "yellow", "pink"],
    season: ["spring", "summer"],
    meaning: "Innocence",
    occasions: ["just-because"],
    fragrance: "none",
    longevity: "medium",
    categories: ["spring", "summer"],
    status: "researching",
  },
  {
    slug: "peony",
    name: "Peony",
    letter: "P",
    shortDescription: "Lush, short-season bloom prized for weddings and romance.",
    colours: ["pink", "white", "red", "peach"],
    season: ["spring", "summer"],
    meaning: "Romance, honour, and prosperity",
    occasions: ["wedding", "anniversary", "romantic", "mothers-day"],
    fragrance: "moderate",
    longevity: "medium",
    petFriendly: false,
    categories: ["romantic", "wedding", "luxury", "popular"],
    status: "published",
    image: unsplashImage("photo-1561181286-d3fee7d55364", "Pink peony with layered petals", "pink-peony-flower-close-up.jpg", "Annie Spratt"),
  },
  {
    slug: "poppy",
    name: "Poppy",
    letter: "P",
    shortDescription: "Delicate petals associated with remembrance; short vase life.",
    colours: ["red", "orange", "pink", "white"],
    season: ["spring", "summer"],
    meaning: "Remembrance and imagination",
    occasions: ["sympathy"],
    fragrance: "none",
    longevity: "short",
    categories: ["wildflowers"],
    status: "researching",
  },
  {
    slug: "protea",
    name: "Protea",
    letter: "P",
    shortDescription: "Southern Hemisphere statement flower used in modern luxury designs.",
    colours: ["pink", "red", "orange"],
    season: ["winter", "spring", "year-round"],
    meaning: "Courage and transformation",
    occasions: ["congratulations", "corporate", "wedding"],
    fragrance: "none",
    longevity: "long",
    categories: ["exotic", "luxury", "long-lasting"],
    status: "researching",
  },
  {
    slug: "primrose",
    name: "Primrose",
    letter: "P",
    shortDescription: "Early spring garden flower, usually gifted as a pot plant.",
    colours: ["yellow", "pink", "purple", "white"],
    season: ["spring"],
    meaning: "Young love",
    occasions: ["just-because"],
    fragrance: "light",
    longevity: "medium",
    categories: ["spring"],
    status: "researching",
  },
  {
    slug: "pansy",
    name: "Pansy",
    letter: "P",
    shortDescription: "Cool-season bedding plant with face-like blooms.",
    colours: ["purple", "yellow", "white", "orange", "mixed"],
    season: ["spring", "winter"],
    meaning: "Thoughtful remembrance",
    occasions: ["just-because", "get-well"],
    fragrance: "light",
    longevity: "medium",
    categories: ["spring", "winter"],
    status: "researching",
  },
  {
    slug: "queen-annes-lace",
    name: "Queen Anne's Lace",
    letter: "Q",
    shortDescription: "Lacy umbel used as a wild, garden-style filler.",
    colours: ["white"],
    season: ["summer"],
    meaning: "Sanctuary",
    occasions: ["wedding", "just-because"],
    fragrance: "light",
    longevity: "short",
    categories: ["wildflowers", "summer", "wedding"],
    status: "researching",
  },
  {
    slug: "ranunculus",
    name: "Ranunculus",
    letter: "R",
    shortDescription: "Layered spring bloom often compared with peonies and roses.",
    colours: ["pink", "peach", "white", "yellow", "red", "orange"],
    season: ["spring", "winter"],
    meaning: "Radiant charm",
    occasions: ["wedding", "anniversary", "romantic", "birthday"],
    fragrance: "light",
    longevity: "medium",
    petFriendly: false,
    categories: ["romantic", "wedding", "spring", "luxury"],
    status: "published",
    image: unsplashImage("photo-1561181286-d3fee7d55364", "Peach ranunculus with many petals", "peach-ranunculus-flower.jpg", "Annie Spratt"),
  },
  {
    slug: "rose",
    name: "Rose",
    letter: "R",
    shortDescription: "The world's best-known cut flower, with colour-specific meanings.",
    colours: ["red", "pink", "white", "yellow", "orange", "peach", "purple"],
    season: ["year-round"],
    meaning: "Love, admiration, and remembrance",
    occasions: ["romantic", "anniversary", "valentines-day", "birthday", "wedding"],
    fragrance: "moderate",
    longevity: "medium",
    petFriendly: true,
    categories: ["popular", "romantic", "wedding", "luxury"],
    status: "published",
    image: unsplashImage("photo-1518621012118-4d0d512fdd5b", "Red garden rose with layered petals", "red-rose-flower-close-up.jpg", "Annie Spratt"),
  },
  {
    slug: "rhododendron",
    name: "Rhododendron",
    letter: "R",
    shortDescription: "Spring shrub; related to azaleas and usually gifted as a plant.",
    colours: ["pink", "purple", "red", "white"],
    season: ["spring"],
    meaning: "Caution and beware in older symbolism",
    occasions: ["housewarming"],
    fragrance: "light",
    longevity: "medium",
    petFriendly: false,
    categories: ["spring"],
    status: "researching",
  },
  {
    slug: "snapdragon",
    name: "Snapdragon",
    letter: "S",
    shortDescription: "Vertical garden spike used to add height in mixed bouquets.",
    colours: ["pink", "yellow", "white", "orange", "red", "purple"],
    season: ["spring", "summer"],
    meaning: "Grace under pressure",
    occasions: ["birthday", "congratulations"],
    fragrance: "light",
    longevity: "medium",
    categories: ["spring", "summer"],
    status: "researching",
  },
  {
    slug: "snowdrop",
    name: "Snowdrop",
    letter: "S",
    shortDescription: "Late-winter woodland bulb signalling the turn toward spring.",
    colours: ["white"],
    season: ["winter"],
    meaning: "Hope and consolation",
    occasions: ["sympathy", "just-because"],
    fragrance: "light",
    longevity: "short",
    categories: ["winter"],
    status: "researching",
  },
  {
    slug: "statice",
    name: "Statice",
    letter: "S",
    shortDescription: "Papery filler that dries well and lasts a long time.",
    colours: ["purple", "pink", "white", "yellow"],
    season: ["year-round"],
    meaning: "Remembrance and success",
    occasions: ["sympathy", "congratulations"],
    fragrance: "none",
    longevity: "long",
    categories: ["long-lasting"],
    status: "researching",
  },
  {
    slug: "stock",
    name: "Stock",
    letter: "S",
    shortDescription: "Spicy-scented spike used in spring and cottage-style bouquets.",
    colours: ["pink", "white", "purple"],
    season: ["spring"],
    meaning: "Lasting beauty and a happy life",
    occasions: ["wedding", "thank-you"],
    fragrance: "strong",
    longevity: "medium",
    categories: ["fragrant", "spring", "wedding"],
    status: "researching",
  },
  {
    slug: "sunflower",
    name: "Sunflower",
    letter: "S",
    shortDescription: "Tall, sunny bloom associated with loyalty and late-summer gifts.",
    colours: ["yellow", "orange"],
    season: ["summer", "autumn"],
    meaning: "Adoration and loyalty",
    occasions: ["birthday", "congratulations", "thank-you", "just-because"],
    fragrance: "none",
    longevity: "medium",
    categories: ["summer", "popular"],
    status: "published",
    image: unsplashImage("photo-1597848212624-e593b1d6c0d6", "Yellow sunflower facing the light", "yellow-sunflower-close-up.jpg", "Annie Spratt"),
  },
  {
    slug: "sweet-pea",
    name: "Sweet Pea",
    letter: "S",
    shortDescription: "Fragrant, ruffled climber with a short, prized cut-flower season.",
    colours: ["pink", "purple", "white", "peach"],
    season: ["spring", "summer"],
    meaning: "Blissful pleasure and departure",
    occasions: ["thank-you", "wedding", "romantic"],
    fragrance: "strong",
    longevity: "short",
    petFriendly: false,
    categories: ["fragrant", "spring", "wedding"],
    status: "researching",
  },
  {
    slug: "tuberose",
    name: "Tuberose",
    letter: "T",
    shortDescription: "Intensely fragrant white spike used in luxury and evening arrangements.",
    colours: ["white"],
    season: ["summer"],
    meaning: "Dangerous pleasure in older floriography",
    occasions: ["wedding", "romantic"],
    fragrance: "strong",
    longevity: "medium",
    categories: ["fragrant", "luxury"],
    status: "researching",
  },
  {
    slug: "tulip",
    name: "Tulip",
    letter: "T",
    shortDescription: "Spring bulb flower with many forms, from Triumph to Parrot.",
    colours: ["red", "pink", "yellow", "white", "orange", "purple"],
    season: ["spring", "winter"],
    meaning: "Affection and perfect love",
    occasions: ["birthday", "romantic", "mothers-day", "congratulations"],
    fragrance: "light",
    longevity: "medium",
    petFriendly: false,
    categories: ["popular", "spring", "romantic"],
    status: "published",
    image: unsplashImage("photo-1520763185298-1b434c919102", "Pink tulips in a spring bunch", "pink-tulip-flowers.jpg", "Annie Spratt"),
  },
  {
    slug: "verbena",
    name: "Verbena",
    letter: "V",
    shortDescription: "Garden annual used more in beds than as a florist cut flower.",
    colours: ["purple", "pink", "red", "white"],
    season: ["summer"],
    meaning: "Enchantment",
    occasions: ["just-because"],
    fragrance: "light",
    longevity: "short",
    categories: ["summer"],
    status: "researching",
  },
  {
    slug: "violet",
    name: "Violet",
    letter: "V",
    shortDescription: "Small, often fragrant spring flower associated with modesty.",
    colours: ["purple", "white"],
    season: ["spring", "winter"],
    meaning: "Modesty and faithfulness",
    occasions: ["romantic", "sympathy"],
    fragrance: "moderate",
    longevity: "short",
    categories: ["spring", "fragrant"],
    status: "researching",
  },
  {
    slug: "water-lily",
    name: "Water Lily",
    letter: "W",
    shortDescription: "Aquatic bloom related to, but distinct from, the sacred lotus.",
    colours: ["white", "pink", "yellow"],
    season: ["summer"],
    meaning: "Enlightenment and peace",
    occasions: ["sympathy"],
    fragrance: "light",
    longevity: "short",
    categories: ["exotic"],
    status: "researching",
  },
  {
    slug: "wisteria",
    name: "Wisteria",
    letter: "W",
    shortDescription: "Cascading spring racemes; dramatic in gardens, rare as a cut crop.",
    colours: ["purple", "white"],
    season: ["spring"],
    meaning: "Welcome and long life",
    occasions: ["wedding"],
    fragrance: "moderate",
    longevity: "short",
    petFriendly: false,
    categories: ["spring", "wedding"],
    status: "researching",
  },
  {
    slug: "yarrow",
    name: "Yarrow",
    letter: "Y",
    shortDescription: "Flat-headed garden perennial used in wild and dried arrangements.",
    colours: ["white", "yellow", "pink"],
    season: ["summer"],
    meaning: "Healing and courage",
    occasions: ["get-well", "just-because"],
    fragrance: "moderate",
    longevity: "long",
    categories: ["summer", "wildflowers", "long-lasting"],
    status: "researching",
  },
  {
    slug: "zinnia",
    name: "Zinnia",
    letter: "Z",
    shortDescription: "Bright summer annual that holds colour well in mixed bouquets.",
    colours: ["pink", "orange", "red", "yellow", "white", "purple"],
    season: ["summer"],
    meaning: "Lasting affection and remembrance of absent friends",
    occasions: ["birthday", "thank-you", "just-because"],
    fragrance: "none",
    longevity: "medium",
    categories: ["summer"],
    status: "researching",
  },
];

export function directoryBySlug(slug: string): FlowerDirectoryEntry | undefined {
  return flowerDirectory.find((f) => f.slug === slug);
}

export function directoryByLetter(): Map<string, FlowerDirectoryEntry[]> {
  const map = new Map<string, FlowerDirectoryEntry[]>();
  for (const flower of flowerDirectory) {
    const list = map.get(flower.letter) ?? [];
    list.push(flower);
    map.set(flower.letter, list);
  }
  return map;
}

export function publishedDirectory(): FlowerDirectoryEntry[] {
  return flowerDirectory.filter((f) => f.status === "published" || f.status === "reviewed");
}
