import type { FlowerOccasion } from "@blossompot/shared";

export type OccasionGuide = {
  slug: FlowerOccasion;
  name: string;
  h1: string;
  seoTitle: string;
  seoDescription: string;
  intro: string;
  recommended: string[];
  colours: string;
  styles: string;
  symbolism: string;
  avoid: string;
  shopCategory?: string;
};

export const occasionGuides: OccasionGuide[] = [
  {
    slug: "birthday",
    name: "Birthday Flowers",
    h1: "Birthday Flowers: Colourful Choices That Feel Personal",
    seoTitle: "Birthday Flowers Guide: Best Blooms & Colours | BlossomPot",
    seoDescription: "Find birthday flowers that feel cheerful rather than overly romantic, plus colour and bouquet ideas.",
    intro:
      "Birthday flowers work best when they match the relationship. Bright mixed bouquets, gerberas, sunflowers and garden-style roses usually read as celebration. A formal dozen red roses can still be right for a partner — they just send a more romantic signal than a mixed birthday bunch.",
    recommended: ["rose", "gerbera", "sunflower", "tulip", "alstroemeria", "dahlia"],
    colours: "Pink, yellow, orange and mixed palettes feel festive. Deep red reads more romantic.",
    styles: "Hand-tied mixed bouquets, sunflower bunches, and flower-and-cake pairings.",
    symbolism: "Cheer and personal thought matter more than a coded Victorian meaning.",
    avoid: "Skip strongly funeral-coded white lilies or white chrysanthemums if the recipient's culture reads them that way.",
    shopCategory: "birthday-gifts",
  },
  {
    slug: "anniversary",
    name: "Anniversary Flowers",
    h1: "Anniversary Flowers: Roses, Peonies & Softer Alternatives",
    seoTitle: "Anniversary Flowers Guide: Roses, Peonies & Meaning | BlossomPot",
    seoDescription: "Choose anniversary flowers with the right level of romance — from classic roses to seasonal peonies.",
    intro:
      "Anniversaries are one of the few times a clearly romantic flower is usually welcome. Red and blush roses remain the default. In late spring, peonies and garden roses feel special. For parents' or friends' anniversaries, elegant mixed blooms are often kinder than intimate red roses.",
    recommended: ["rose", "peony", "lisianthus", "ranunculus", "orchid"],
    colours: "Red, blush, cream and soft peach. Bright mixed rainbows can feel less 'milestone'.",
    styles: "Dozen roses, garden-style posies, or an orchid plant for a lasting gift.",
    symbolism: "Colour still carries Western romantic conventions; the note should name the year or a shared detail.",
    avoid: "Overly public workplace deliveries unless you know they will be welcome.",
    shopCategory: "anniversary-gifts",
  },
  {
    slug: "valentines-day",
    name: "Valentine's Day Flowers",
    h1: "Valentine's Day Flowers: Roses and the Real Supply Story",
    seoTitle: "Valentine's Day Flowers Guide | BlossomPot",
    seoDescription: "Why red roses dominate Valentine's Day, what else to send, and how season and demand affect availability.",
    intro:
      "Valentine's Day sits in northern winter, so almost every rose is a greenhouse or import stem — not a garden flower. Demand, not botany, drives price. Red roses remain the expected romantic gift in much of the US, UK, Canada, Europe, Australia and the UAE. If you want to stand out, garden-style roses, ranunculus or a well-chosen mixed red-and-blush design can feel less automatic.",
    recommended: ["rose", "ranunculus", "tulip", "orchid"],
    colours: "Red first, then blush and deep pink. Yellow can read as friendship unless the relationship is already clear.",
    styles: "Classic dozens, compact luxury posies, or a potted orchid if travel time is long.",
    symbolism: "Red roses are the cultural shorthand for romantic love on this date. That is convention, amplified by the holiday.",
    avoid: "Do not claim same-day delivery unless the product and location actually support it.",
    shopCategory: "valentines-day-gifts",
  },
  {
    slug: "mothers-day",
    name: "Mother's Day Flowers",
    h1: "Mother's Day Flowers: US, UK and Australian Dates Differ",
    seoTitle: "Mother's Day Flowers Guide: US, UK & Australia | BlossomPot",
    seoDescription: "Mother's Day flowers change with the date: May in the US and Canada, March in the UK, May autumn mums in Australia.",
    intro:
      "Mother's Day is not one global date. The United States and Canada celebrate on the second Sunday in May. The UK celebrates Mothering Sunday in March (the fourth Sunday of Lent). Australia and New Zealand celebrate in May — which is autumn there, so chrysanthemums are a traditional flower. Pink carnations have a specific US history. Choose what is seasonal and culturally comfortable, not a copied US list for every country.",
    recommended: ["carnation", "rose", "tulip", "peony", "hydrangea", "chrysanthemum"],
    colours: "Soft pinks, creams and mixed pastels are widely safe. Follow family tradition if they have one.",
    styles: "Garden mixed bouquets, carnation bunches (US), tulips (UK March), mums (Australia May).",
    symbolism: "US pink-carnation history is real but not universal. UK Mothering Sunday is older and seasonal in a different month.",
    avoid: "Do not send true lilies to a home with cats. Do not assume Australian mums are 'wrong' because a US guide prefers peonies.",
    shopCategory: "mothers-day-gifts",
  },
  {
    slug: "wedding",
    name: "Wedding Flowers",
    h1: "Wedding Flowers: Season-First Choices",
    seoTitle: "Wedding Flowers Guide: Seasonal Blooms & Styles | BlossomPot",
    seoDescription: "Plan wedding flowers around real seasons — peonies, garden roses, hydrangeas and honest substitutions.",
    intro:
      "The best wedding flower is the one that is actually in good supply on the date. Peonies in a northern June are a different proposition from peonies in a northern January. Garden roses, lisianthus, ranunculus and hydrangeas cover most romantic briefs when the hero flower is out of season.",
    recommended: ["peony", "rose", "ranunculus", "hydrangea", "lisianthus", "calla-lily", "babys-breath"],
    colours: "Blush, cream, white and soft peach dominate; saturated palettes work when the dress and venue support them.",
    styles: "Garden hand-ties, structured calla lines, hydrangea volume, and boutonniere work.",
    symbolism: "White still signals formality in many Western weddings; it is not a purity test.",
    avoid: "Locking a flower list before checking season and budget. Highly fragrant Orientals in a small, hot room.",
    shopCategory: "wedding-gifts",
  },
  {
    slug: "engagement",
    name: "Engagement Flowers",
    h1: "Engagement Flowers: Celebratory, Not Funeral-Formal",
    seoTitle: "Engagement Flowers Guide | BlossomPot",
    seoDescription: "Flower ideas for engagements — romantic without copying a funeral or office look.",
    intro: "Engagement flowers can be romantic or simply celebratory. Garden roses, peonies in season, and champagne-toned mixed bouquets work well.",
    recommended: ["rose", "peony", "ranunculus", "lisianthus"],
    colours: "Blush, cream and soft reds.",
    styles: "A luxury posy or a bottle-and-bloom hamper if you are celebrating as friends.",
    symbolism: "Romance is welcome; keep the card specific.",
    avoid: "White lily sympathy styling.",
  },
  {
    slug: "congratulations",
    name: "Congratulations Flowers",
    h1: "Congratulations Flowers: Bright, Upright, Unambiguous",
    seoTitle: "Congratulations Flowers Guide | BlossomPot",
    seoDescription: "Best flowers for promotions, exams and new chapters — cheerful without mixed funeral signals.",
    intro: "Congratulations designs should look upward and bright. Sunflowers, gerberas, colourful roses and orchids are reliable. Avoid sombre white sympathy shapes.",
    recommended: ["sunflower", "gerbera", "orchid", "rose", "alstroemeria"],
    colours: "Yellow, orange, bright pink and mixed.",
    styles: "Upright mixed bouquets or a flowering plant for a desk.",
    symbolism: "Energy and pride, not romance, unless the achievement is shared as a couple.",
    avoid: "Funeral lilies and white-mum cultural clashes.",
  },
  {
    slug: "thank-you",
    name: "Thank You Flowers",
    h1: "Thank You Flowers: Gratitude Without Overstatement",
    seoTitle: "Thank You Flowers Guide | BlossomPot",
    seoDescription: "Soft, useful thank-you flower ideas — pinks, creams and lasting plants.",
    intro: "Thank-you flowers should feel warm, not romantic unless that is the relationship. Pink roses, hydrangeas, mixed pastels and orchids are safe.",
    recommended: ["rose", "hydrangea", "lisianthus", "freesia", "orchid"],
    colours: "Pink, cream, lavender.",
    styles: "Compact mixed bouquets or a plant.",
    symbolism: "Appreciation. Keep the note specific about what you are thanking them for.",
    avoid: "A dozen red roses to a colleague — it can be misread.",
  },
  {
    slug: "get-well",
    name: "Get Well Soon Flowers",
    h1: "Get Well Flowers: Cheerful and Practical",
    seoTitle: "Get Well Soon Flowers Guide | BlossomPot",
    seoDescription: "Choose get-well flowers that are bright, lightly scented and easy to care for.",
    intro: "Get-well gifts should lift a room without overwhelming a small space. Gerberas, alstroemeria and soft mixed bunches work. Avoid heavy Oriental lily scent in a sickroom and never send true lilies to a home with cats.",
    recommended: ["gerbera", "alstroemeria", "sunflower", "tulip"],
    colours: "Yellow, pink, orange.",
    styles: "Light mixed bunches; plants if the recovery will be long.",
    symbolism: "Encouragement, not drama.",
    avoid: "Intense fragrance, messy pollen, and anything the household cannot water.",
  },
  {
    slug: "sympathy",
    name: "Sympathy Flowers",
    h1: "Sympathy Flowers: Respect First, Culture Second",
    seoTitle: "Sympathy Flowers Guide | BlossomPot",
    seoDescription: "A careful guide to sympathy flowers, including cultural differences around lilies and chrysanthemums.",
    intro:
      "Sympathy flowers should be chosen with the family's culture in mind. In much of the US and UK, white lilies, white roses and mixed whites are common. In several European countries, chrysanthemums are cemetery flowers. In some East Asian contexts, white and yellow chrysanthemums carry mourning. When unsure, ask the family or choose a simple mixed white-and-green arrangement with a short card.",
    recommended: ["lily", "rose", "calla-lily", "chrysanthemum", "orchid"],
    colours: "White, cream and soft green are widely used in Western sympathy. Follow local custom.",
    styles: "Sheaves, baskets, and simple vase arrangements rather than celebratory rainbows — unless the family asked for a celebration of life.",
    symbolism: "Respect and remembrance. Do not invent religious meaning the family does not share.",
    avoid: "Bright party palettes unless requested. True lilies in a house with cats.",
  },
  {
    slug: "funeral",
    name: "Funeral Flowers",
    h1: "Funeral Flowers: Formal Sympathy",
    seoTitle: "Funeral Flowers Guide | BlossomPot",
    seoDescription: "How funeral flowers differ from general sympathy gifts, and what to avoid culturally.",
    intro: "Funeral flowers are usually more formal than a sympathy vase sent to a home. White lilies, roses and, in some countries, chrysanthemums are typical. Follow the family's requests and the venue rules.",
    recommended: ["lily", "rose", "calla-lily", "chrysanthemum", "gladiolus"],
    colours: "White and green unless the family specified a colour.",
    styles: "Casket sprays, standing sprays and sheaves are traditional; not every florist or vendor offers every form.",
    symbolism: "Farewell and honour.",
    avoid: "Sending a festive birthday-style mix to a service without being asked.",
  },
  {
    slug: "new-baby",
    name: "New Baby Flowers",
    h1: "New Baby Flowers: Soft, Safe, Unfussy",
    seoTitle: "New Baby Flowers Guide | BlossomPot",
    seoDescription: "Gentle flower ideas for a new baby — and what to skip around pets and strong scent.",
    intro: "Pastel mixed bouquets, baby's breath clouds and compact designs suit a new-baby gift. Avoid overpowering scent in a small home and skip true lilies if there are cats.",
    recommended: ["babys-breath", "rose", "lisianthus", "gerbera"],
    colours: "Soft pink, cream, yellow, pale blue — without assuming gender stereotypes if you are unsure.",
    styles: "Smaller bunches that fit a kitchen counter.",
    symbolism: "Welcome and gentleness.",
    avoid: "Huge formal sympathy shapes and heavy Oriental lilies.",
  },
  {
    slug: "housewarming",
    name: "Housewarming Flowers",
    h1: "Housewarming Flowers and Plants",
    seoTitle: "Housewarming Flowers Guide | BlossomPot",
    seoDescription: "Flowers and plants that make sense for a new home — orchids, hydrangeas and lasting gifts.",
    intro: "A housewarming gift should survive the first busy week. Orchids, hydrangeas and mixed neutrals work. A plant often outlasts a cut bunch.",
    recommended: ["orchid", "hydrangea", "anthurium", "rose"],
    colours: "Cream, green, soft pink.",
    styles: "A potted orchid or a substantial mixed arrangement.",
    symbolism: "Welcome and good wishes for the house.",
    avoid: "High-maintenance gardenias unless you know they garden.",
  },
  {
    slug: "apology",
    name: "Apology Flowers",
    h1: "Apology Flowers: Sincere, Not Theatrical",
    seoTitle: "Apology Flowers Guide | BlossomPot",
    seoDescription: "How to send apology flowers without overdoing romance or empty grand gestures.",
    intro: "Apology flowers only help if the note is specific. Soft roses, lisianthus or a simple mixed bunch are enough. A giant red-rose statement can feel like pressure.",
    recommended: ["rose", "lisianthus", "tulip", "freesia"],
    colours: "Soft pink, cream, peach.",
    styles: "A modest hand-tie and an honest sentence.",
    symbolism: "Sincerity. Do not hide behind 'flower language' instead of an apology.",
    avoid: "Public workplace scenes and joke cards.",
  },
  {
    slug: "romantic",
    name: "Romantic Flowers",
    h1: "Romantic Flowers Beyond the Default Dozen",
    seoTitle: "Romantic Flowers Guide | BlossomPot",
    seoDescription: "Romantic flower ideas: roses, peonies, garden roses and when to choose something softer.",
    intro: "Romance still starts with roses for many people, and that is fine. Peonies, garden roses, ranunculus and scented gardenias offer other textures when the season allows.",
    recommended: ["rose", "peony", "ranunculus", "gardenia", "tulip"],
    colours: "Red, blush, burgundy, cream.",
    styles: "Dozen roses, garden posies, or a single luxurious variety.",
    symbolism: "Affection. Colour conventions are Western and optional.",
    avoid: "Sending the most romantic styling to someone who has not welcomed that signal.",
    shopCategory: "anniversary-gifts",
  },
  {
    slug: "just-because",
    name: "Just Because Flowers",
    h1: "Just Because Flowers: No Occasion Required",
    seoTitle: "Just Because Flowers Guide | BlossomPot",
    seoDescription: "Everyday flower ideas when there is no holiday — cheerful, seasonal and low-pressure.",
    intro: "The best just-because bouquet is seasonal and low-pressure. Tulips in spring, sunflowers in summer, mixed garden roses whenever they look good.",
    recommended: ["tulip", "sunflower", "alstroemeria", "gerbera", "rose"],
    colours: "Whatever is plentiful that week.",
    styles: "Informal mixed bunches.",
    symbolism: "Attention. That is enough.",
    avoid: "Over-explaining. Let the card stay short.",
  },
  {
    slug: "graduation",
    name: "Graduation Flowers",
    h1: "Graduation Flowers: Bright and Photographable",
    seoTitle: "Graduation Flowers Guide | BlossomPot",
    seoDescription: "Cheerful graduation flower ideas that photograph well and travel to a ceremony.",
    intro: "Graduation flowers should be bright and easy to carry. Gerberas, sunflowers and colourful roses work. Skip dripping hydrangeas on a hot campus lawn.",
    recommended: ["sunflower", "gerbera", "rose", "alstroemeria"],
    colours: "School colours if you know them; otherwise bright mixed.",
    styles: "Hand-tied bunches that survive a hug and a photo.",
    symbolism: "Pride and a new chapter.",
    avoid: "Fragile gardenias and heavy scented lilies in a crowded hall.",
  },
  {
    slug: "corporate",
    name: "Corporate Flowers",
    h1: "Corporate Flowers: Neutral, Lasting, Uncontroversial",
    seoTitle: "Corporate Flowers Guide | BlossomPot",
    seoDescription: "Office and client flower ideas that stay professional — orchids, clean whites and lasting plants.",
    intro: "Corporate flowers should be neat, lightly scented and culturally safe. Orchids, white-and-green arrangements and quality mixed neutrals beat romantic red roses.",
    recommended: ["orchid", "calla-lily", "rose", "anthurium"],
    colours: "White, green, soft purple. Avoid romantic red unless the brief is celebratory and personal.",
    styles: "Potted orchids, compact vase arrangements.",
    symbolism: "Respect and congratulations — not courtship.",
    avoid: "Heavy fragrance in open-plan offices and funeral-coded white mums in the wrong country.",
    shopCategory: "gift-hampers",
  },
];

export function getOccasionGuide(slug: string): OccasionGuide | undefined {
  return occasionGuides.find((o) => o.slug === slug);
}
